In [1]:
import pandas as pd
countries = pd.Series(
    data = ['Англия', 'Канада', 'США', 'Россия', 'Украина', 'Беларусь', 'Казахстан'],
    index = ['UK', 'CA', 'US', 'RU', 'UA', 'BY', 'KZ'],
    name = 'countries'
)
display(countries)

UK       Англия
CA       Канада
US          США
RU       Россия
UA      Украина
BY     Беларусь
KZ    Казахстан
Name: countries, dtype: object

In [2]:
countries = pd.Series({
    'UK': 'Англия',
    'CA': 'Канада',
    'US' : 'США',
    'RU': 'Россия',
    'UA': 'Украина',
    'BY': 'Беларусь',
    'KZ': 'Казахстан'},
    name = 'countries'
)
display(countries)

UK       Англия
CA       Канада
US          США
RU       Россия
UA      Украина
BY     Беларусь
KZ    Казахстан
Name: countries, dtype: object

In [3]:
print(countries.loc[['US', 'RU', 'UK']])
print(countries.iloc[1:4])

US       США
RU    Россия
UK    Англия
Name: countries, dtype: object
CA    Канада
US       США
RU    Россия
Name: countries, dtype: object

In [4]:
import pandas as pd

def create_medications(names, counts):
    medications = pd.Series(
    data = counts,
    index = names)
#     name = 'medications')
    return medications

def get_percent(medications, name):
    return medications.loc[name]/medications.sum()*100
    
names=['chlorhexidine', 'cyntomycin', 'afobazol']
counts=[15, 18, 7]
medications = create_medications(names, counts)

print(get_percent(medications, "chlorhexidine")) #37.5

37.5

In [5]:
import pandas as pd
countries_df = pd.DataFrame({
    'country': ['Англия', 'Канада', 'США', 'Россия', 'Украина', 'Беларусь', 'Казахстан'],
    'population': [56.29, 38.05, 322.28, 146.24, 45.5, 9.5, 17.04],
    'area': [133396, 9984670, 9826630, 17125191, 603628, 207600, 2724902]
})
countries_df.index = ['UK', 'CA', 'US', 'RU', 'UA', 'BY', 'KZ']
display(countries_df)

      country  population      area
UK     Англия       56.29    133396
CA     Канада       38.05   9984670
US        США      322.28   9826630
RU     Россия      146.24  17125191
UA    Украина       45.50    603628
BY   Беларусь        9.50    207600
KZ  Казахстан       17.04   2724902

In [6]:
import pandas as pd
countries_df = pd.DataFrame(
    data = [
        ['Англия', 56.29, 133396],
        ['Канада', 38.05, 9984670],
        ['США', 322.28, 9826630],
        ['Россия', 146.24, 17125191],
        ['Украина', 45.5, 603628],
        ['Беларусь', 9.5, 207600],
        ['Казахстан', 17.04, 2724902]
    ],
    columns= ['country', 'population', 'area'],
    index = ['UK', 'CA', 'US', 'RU', 'UA', 'BY', 'KZ']
)
countries_df

      country  population      area
UK     Англия       56.29    133396
CA     Канада       38.05   9984670
US        США      322.28   9826630
RU     Россия      146.24  17125191
UA    Украина       45.50    603628
BY   Беларусь        9.50    207600
KZ  Казахстан       17.04   2724902

In [7]:
countries_df.mean(axis=0, numeric_only=True)

population    9.070000e+01
area          5.800860e+06
dtype: float64

In [8]:
countries_df.mean(axis=1, numeric_only=True)

UK      66726.145
CA    4992354.025
US    4913476.140
RU    8562668.620
UA     301836.750
BY     103804.750
KZ    1362459.520
dtype: float64

In [9]:
countries_df.population

UK     56.29
CA     38.05
US    322.28
RU    146.24
UA     45.50
BY      9.50
KZ     17.04
Name: population, dtype: float64

In [10]:
countries_df['population']

UK     56.29
CA     38.05
US    322.28
RU    146.24
UA     45.50
BY      9.50
KZ     17.04
Name: population, dtype: float64

In [11]:
type(countries_df.population)

pandas.core.series.Series

In [12]:
# 1Получим площадь Великобритании:

countries_df.loc['UK', 'area']
# 2Получим население и площадь, соответствующие России:

countries_df.loc['RU', ['population', 'area']]
# 3Сделаем вырезку из таблицы и получим информацию о населении и площади, соответствующую Украине, Беларуси и Казахстану:

countries_df.loc[['UA', 'BY', 'KZ'],['population', 'area']]
# или
countries_df.iloc[4:8, 1:3]

    population     area
UA       45.50   603628
BY        9.50   207600
KZ       17.04  2724902

In [13]:
pd.DataFrame([[0,1], [1, 0]], columns=['А', 'B'])

   А  B
0  0  1
1  1  0

In [14]:
pd.DataFrame({'А': [0, 1], 'B': [1, 0]})

   А  B
0  0  1
1  1  0

In [15]:
import pandas as pd 

def create_companyDF(income, expenses, years):
    df = pd.DataFrame({'Income':income,'Expenses':expenses})
    df.index = years
    
    return df
    
def get_profit(df, year):
    if not year in df.index:
        return None
    return df.loc[year]['Income']-df.loc[year]['Expenses']
    

income = [478, 512, 196]
expenses = [156, 130, 270]
years = [2018, 2019, 2020]
df = create_companyDF(income, expenses, years)
print(df)
print(get_profit(df, 2018))

      Income  Expenses
2018     478       156
2019     512       130
2020     196       270
322

In [16]:
countries_df = pd.DataFrame({
    'country': ['Англия', 'Канада', 'США', 'Россия', 'Украина', 'Беларусь', 'Казахстан'],
    'population': [56.29, 38.05, 322.28, 146.24, 45.5, 9.5, 17.04],
    'area': [133396, 9984670, 9826630, 17125191, 603628, 207600, 2724902]
})

countries_df.to_csv('data/countries.csv', index=False, sep=';')

In [17]:
countries_data = pd.read_csv('data/countries.csv', sep=';')
display(countries_data)

     country  population      area
0     Англия       56.29    133396
1     Канада       38.05   9984670
2        США      322.28   9826630
3     Россия      146.24  17125191
4    Украина       45.50    603628
5   Беларусь        9.50    207600
6  Казахстан       17.04   2724902

In [18]:
data = pd.read_csv('https://raw.githubusercontent.com/esabunor/MLWorkspace/master/melb_data.csv')
display(data)

,Unnamed: 0,Suburb,Address,Rooms,Type,Price,Method,SellerG,Date,Distance,...,Bathroom,Car,Landsize,BuildingArea,YearBuilt,CouncilArea,Lattitude,Longtitude,Regionname,Propertycount
0,1,Abbotsford,85 Turner St,2,h,1480000.0,S,Biggin,3/12/2016,2.5,...,1.0,1.0,202.0,NaN,NaN,Yarra,-37.79960,144.99840,Northern Metropolitan,4019.0
1,2,Abbotsford,25 Bloomburg St,2,h,1035000.0,S,Biggin,4/02/2016,2.5,...,1.0,0.0,156.0,79.0,1900.0,Yarra,-37.80790,144.99340,Northern Metropolitan,4019.0
2,4,Abbotsford,5 Charles St,3,h,1465000.0,SP,Biggin,4/03/2017,2.5,...,2.0,0.0,134.0,150.0,1900.0,Yarra,-37.80930,144.99440,Northern Metropolitan,4019.0
3,5,Abbotsford,40 Federation La,3,h,850000.0,PI,Biggin,4/03/2017,2.5,...,2.0,1.0,94.0,NaN,NaN,Yarra,-37.79690,144.99690,Northern Metropolitan,4019.0
4,6,Abbotsford,55a Park St,4,h,1600000.0,VB,Nelson,4/06/2016,2.5,...,1.0,2.0,120.0,142.0,2014.0,Yarra,-37.80720,144.99410,Northern Metropolitan,4019.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18391,23540,Williamstown,8/2 Thompson St,2,t,622500.0,SP,Greg,26/08/2017,6.8,...,2.0,1.0,NaN,89.0,2010.0,NaN,-37.86393,144.90484,Western Metropolitan,6380.0
18392,23541,Williamstown,96 Verdon St,4,h,2500000.0,PI,Sweeney,26/08/2017,6.8,...,1.0,5.0,866.0,157.0,1920.0,NaN,-37.85908,144.89299,Western Metropolitan,6380.0
18393,23544,Yallambie,17 Amaroo Wy,4,h,1100000.0,S,Buckingham,26/08/2017,12.7,...,3.0,2.0,NaN,NaN,NaN,NaN,-37.72006,145.10547,Northern Metropolitan,1369.0
18394,23545,Yarraville,6 Agnes St,4,h,1285000.0,SP,Village,26/08/2017,6.3,...,1.0,1.0,362.0,112.0,1920.0,NaN,-37.81188,144.88449,Western Metropolitan,6543.0
18395,23546,Yarraville,33 Freeman St,4,h,1050000.0,VB,Village,26/08/2017,6.3,...,2.0,2.0,NaN,139.0,1950.0,NaN,-37.81829,144.87404,Western Metropolitan,6543.0

In [19]:
# index — номер строки
# Suburb — наименование пригорода
# Address — адрес
# Rooms — количество комнат в помещении
# Type — тип здания (h — дом, коттедж, вилла, терраса; u — блочный, дуплексный дом; t — таунхаус)
# Price — цена помещения
# Method — метод продажи 
# SellerG — риэлторская компания
# Date — дата продажи (в формате день/месяц/год)
# Distance — расстояния до объекта от центра Мельбурна 
# Postcode — почтовый индекс
# Bedroom — количество спален
# Bathroom — количество ванных комнат
# Car — количество парковочных мест
# Landsize — площадь прилегающей территории
# BuildingArea — площадь здания
# YearBuilt — год постройки
# CouncilArea — региональное управление
# Lattitude — географическая широта
# Longitude — географическая долгота
# Regionname — наименование района Мельбурна
# Propertycount — количество объектов недвижимости в районе
# Coordinates — широта и долгота, объединённые в кортеж
melb_data = pd.read_csv('data/melb_data.csv', sep=',')
display(melb_data.head())

,index,Suburb,Address,Rooms,Type,Price,Method,SellerG,Date,Distance,...,Car,Landsize,BuildingArea,YearBuilt,CouncilArea,Lattitude,Longtitude,Regionname,Propertycount,Coordinates
0,0,Abbotsford,85 Turner St,2,h,1480000.0,S,Biggin,3/12/2016,2.5,...,1.0,202.0,126.0,1970.0,Yarra,-37.7996,144.9984,Northern Metropolitan,4019.0,"-37.7996, 144.9984"
1,1,Abbotsford,25 Bloomburg St,2,h,1035000.0,S,Biggin,4/02/2016,2.5,...,0.0,156.0,79.0,1900.0,Yarra,-37.8079,144.9934,Northern Metropolitan,4019.0,"-37.8079, 144.9934"
2,2,Abbotsford,5 Charles St,3,h,1465000.0,SP,Biggin,4/03/2017,2.5,...,0.0,134.0,150.0,1900.0,Yarra,-37.8093,144.9944,Northern Metropolitan,4019.0,"-37.8093, 144.9944"
3,3,Abbotsford,40 Federation La,3,h,850000.0,PI,Biggin,4/03/2017,2.5,...,1.0,94.0,126.0,1970.0,Yarra,-37.7969,144.9969,Northern Metropolitan,4019.0,"-37.7969, 144.9969"
4,4,Abbotsford,55a Park St,4,h,1600000.0,VB,Nelson,4/06/2016,2.5,...,2.0,120.0,142.0,2014.0,Yarra,-37.8072,144.9941,Northern Metropolitan,4019.0,"-37.8072, 144.9941"

In [20]:
print(melb_data.tail(2))
melb_data.shape

       index        Suburb       Address  Rooms Type      Price Method  \
13578  13578  Williamstown  96 Verdon St      4    h  2500000.0     PI
13579  13579    Yarraville    6 Agnes St      4    h  1285000.0     SP

       SellerG        Date  Distance  ...  Car  Landsize  BuildingArea  \
13578  Sweeney  26/08/2017       6.8  ...  5.0     866.0         157.0
13579  Village  26/08/2017       6.3  ...  1.0     362.0         112.0

       YearBuilt  CouncilArea  Lattitude  Longtitude            Regionname  \
13578     1920.0          NaN  -37.85908   144.89299  Western Metropolitan
13579     1920.0          NaN  -37.81188   144.88449  Western Metropolitan

       Propertycount           Coordinates
13578         6380.0  -37.85908, 144.89299
13579         6543.0  -37.81188, 144.88449

[2 rows x 23 columns]

(13580, 23)

In [21]:
import numpy as np
print(melb_data.iloc[15]['Price'])
print(melb_data.iloc[90]['Date'])

# Во сколько раз площадь прилегающей территории, на которой находится здание с индексом 3521, 
# больше площади участка, на котором находится здание с индексом 1690? Ответ округлите до целого числа.
print(round(melb_data.iloc[3521]['Landsize']/melb_data.iloc[1690]['Landsize'],0))

1310000.0
10/09/2016
3.0

In [22]:
print(melb_data.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13580 entries, 0 to 13579
Data columns (total 23 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   index          13580 non-null  int64
 1   Suburb         13580 non-null  object
 2   Address        13580 non-null  object
 3   Rooms          13580 non-null  int64
 4   Type           13580 non-null  object
 5   Price          13580 non-null  float64
 6   Method         13580 non-null  object
 7   SellerG        13580 non-null  object
 8   Date           13580 non-null  object
 9   Distance       13580 non-null  float64
 10  Postcode       13580 non-null  int64
 11  Bedroom        13580 non-null  float64
 12  Bathroom       13580 non-null  float64
 13  Car            13580 non-null  float64
 14  Landsize       13580 non-null  float64
 15  BuildingArea   13580 non-null  float64
 16  YearBuilt      13580 non-null  float64
 17  CouncilArea    12211 non-null  object
 18  Lattitude      13580 non-null  float64
 19  Longtitude     13580 non-null  float64
 20  Regionname     13580 non-null  object
 21  Propertycount  13580 non-null  float64
 22  Coordinates    13580 non-null  object
dtypes: float64(11), int64(3), object(9)
memory usage: 2.4+ MB
None

In [23]:
# melb_data.dropna(how='all')
# melb_data..fillna(0)
# frame3.fillna({'ball':1,'mug':0,'pen':99})

# Сколько пропущенных значений в столбце CouncilArea?
len(melb_data[melb_data['CouncilArea'].notnull()==False])

1369

In [24]:
melb_data['Car'] = melb_data['Car'].astype('int64')
melb_data['Bedroom'] = melb_data['Bedroom'].astype('int64')
melb_data['Bathroom'] = melb_data['Bathroom'].astype('int64')
melb_data['Propertycount'] = melb_data['Propertycount'].astype('int64')
melb_data['YearBuilt'] = melb_data['YearBuilt'].astype('int64')
melb_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13580 entries, 0 to 13579
Data columns (total 23 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   index          13580 non-null  int64
 1   Suburb         13580 non-null  object
 2   Address        13580 non-null  object
 3   Rooms          13580 non-null  int64
 4   Type           13580 non-null  object
 5   Price          13580 non-null  float64
 6   Method         13580 non-null  object
 7   SellerG        13580 non-null  object
 8   Date           13580 non-null  object
 9   Distance       13580 non-null  float64
 10  Postcode       13580 non-null  int64
 11  Bedroom        13580 non-null  int64
 12  Bathroom       13580 non-null  int64
 13  Car            13580 non-null  int64
 14  Landsize       13580 non-null  float64
 15  BuildingArea   13580 non-null  float64
 16  YearBuilt      13580 non-null  int64
 17  CouncilArea    12211 non-null  object
 18  Lattitude      13580 non-null  float64
 19  Longtitude     13580 non-null  float64
 20  Regionname     13580 non-null  object
 21  Propertycount  13580 non-null  int64
 22  Coordinates    13580 non-null  object
dtypes: float64(6), int64(8), object(9)
memory usage: 2.4+ MB

In [25]:
# Сколько столбцов после преобразования типов имеет целочисленный тип данных?
print(len(melb_data.select_dtypes(include='int64').columns))
display(len(melb_data.select_dtypes(include='int64').columns))

8

8

In [26]:
melb_data.describe().loc[:, ['Distance', 'BuildingArea' , 'Price']]

           Distance  BuildingArea         Price
count  13580.000000  13580.000000  1.358000e+04
mean      10.137776    139.633972  1.075684e+06
std        5.868725    392.217403  6.393107e+05
min        0.000000      0.000000  8.500000e+04
25%        6.100000    122.000000  6.500000e+05
50%        9.200000    126.000000  9.030000e+05
75%       13.000000    129.940000  1.330000e+06
max       48.100000  44515.000000  9.000000e+06

In [27]:
# количество непустых строк (count);
# количество уникальных значений (unique);
# самое частое значение — мода —  (top);
# частота — объём использования — этого значения (freq) для каждого столбца типа object исходной таблицы.
melb_data.describe(include=['object'])

,Suburb,Address,Type,Method,SellerG,Date,CouncilArea,Regionname,Coordinates
count,13580,13580,13580,13580,13580,13580,12211,13580,13580
unique,314,13378,3,5,268,58,33,8,13097
top,Reservoir,5 Charles St,h,S,Nelson,27/05/2017,Moreland,Southern Metropolitan,"-37.8361, 144.9966"
freq,359,3,9449,9022,1565,473,1163,4695,12

In [28]:
# Для того чтобы определить, сколько раз в столбце повторяется каждый из вариантов значений 
# (т.е. найти частоту для каждого уникального знания), используется метод value_counts().
melb_data['Regionname'].value_counts()

Regionname
Southern Metropolitan         4695
Northern Metropolitan         3890
Western Metropolitan          2948
Eastern Metropolitan          1471
South-Eastern Metropolitan     450
Eastern Victoria                53
Northern Victoria               41
Western Victoria                32
Name: count, dtype: int64

In [29]:
# Чтобы сделать вывод более интерпретируемым и понятным, можно воспользоваться параметром normalize. 
# При установке значения этого параметра на True результат будет представляться в виде доли (относительной частоты):
melb_data['Regionname'].value_counts(normalize=True)

Regionname
Southern Metropolitan         0.345729
Northern Metropolitan         0.286451
Western Metropolitan          0.217084
Eastern Metropolitan          0.108321
South-Eastern Metropolitan    0.033137
Eastern Victoria              0.003903
Northern Victoria             0.003019
Western Victoria              0.002356
Name: proportion, dtype: float64

In [30]:
# Сколько процентов от общего количества домов составляют таунхаусы (тип объекта — t)?
print(len(melb_data[melb_data['Type']=='t'])/len(melb_data))
print(melb_data[melb_data['Type']=='t'].shape[0]/melb_data.shape[0])

0.08203240058910162
0.08203240058910162

In [31]:
# .count()	Количество непустых значений
# .mean()	Среднее значение
# .min()	Минимальное значение
# .max()	Максимальное значение
# .var()	Дисперсия
# .std()	Стандартное отклонение
# .sum()	Сумма
# .quantile(x)	Квантиль уровня x
# .nunique()	Число уникальных значений
# Если один из этих методов применить ко всему DataFrame, то в результате его работы будет получен объект типа Series, 
# в котором в качестве индексов будут выступать наименования столбцов, а в качестве значений — статистический показатель. 
# В случае применения метода к отдельному столбцу результатом вычислений станет число.
# axis  — определяет, подсчитывать параметр по строкам или по столбцам;
# numeric_only — определяет, вычислять параметры только по числовым столбцам/строкам или нет (True/False).

# Вычислим среднюю цену на объекты недвижимости:

print(melb_data['Price'].mean())
# 1075684.079455081
# Найдём максимальное количество парковочных мест:

print(melb_data['Car'].max())
# 10
# А теперь представим, что риэлторская ставка для всех компаний за продажу недвижимости составляет 12%. 
# Найдём общую прибыльность риэлторского бизнеса в Мельбурне. Результат округлим до сотых:

rate = 0.12
income = melb_data['Price'].sum() * rate
print('Total income of real estate agencies:', round(income, 2))
# Total income of real estate agencies: 1752934775.88
# Найдём, насколько медианная площадь территории отличается от её среднего значения. 
# Вычислим модуль разницы между медианой и средним и разделим результат на среднее, чтобы получить отклонение в долях:

landsize_median = melb_data['Landsize'].median() 
landsize_mean =  melb_data['Landsize'].mean()
print(abs(landsize_median - landsize_mean)/landsize_mean)
# 0.21205713983546193

# Вычислим, какое число комнат чаще всего представлено на рынке недвижимости (мода):
# Модальных значений может быть несколько, то есть несколько значений могут встречаться одинаковое количество раз. 
# Поэтому метод mode(), в отличие от агрегирующих методов, возвращает не одно число, а серию.
print(melb_data['Rooms'].mode())

# Метод mode() может быть использован не только с числовыми столбцами, но и со столбцами типа object. 
# Так, например, с помощью следующего кода можно найти наиболее распространённое название района:
print(melb_data['Regionname'].mode())

# Чему равно максимальное количество домов на продажу в районе (Propertycount)?
print(melb_data['Propertycount'].max())

# Чему равно отклонение (в процентах) медианного значения площади здания от его среднего значения?
print((melb_data['BuildingArea'].median()-melb_data['BuildingArea'].mean())/melb_data['BuildingArea'].mean()*100)

# Сколько спален чаще всего встречается в домах в Мельбурне?
melb_data['Bedroom'].mode()

1075684.079455081
10
Total income of real estate agencies: 1752934775.88
0.21205713983546193
0    3
Name: Rooms, dtype: int64
0    Southern Metropolitan
Name: Regionname, dtype: object
21650
-9.764079662364534

0    3
Name: Bedroom, dtype: int64

In [32]:
mask = melb_data['Price'] > 2000000
display(mask)
display(melb_data[mask].head())

0        False
1        False
2        False
3        False
4        False
         ...
13575    False
13576    False
13577    False
13578     True
13579    False
Name: Price, Length: 13580, dtype: bool

,index,Suburb,Address,Rooms,Type,Price,Method,SellerG,Date,Distance,...,Car,Landsize,BuildingArea,YearBuilt,CouncilArea,Lattitude,Longtitude,Regionname,Propertycount,Coordinates
80,80,Albert Park,112 Beaconsfield Pde,3,h,2850000.0,PI,Buxton,4/03/2017,3.3,...,0,211.0,198.0,1890,Port Phillip,-37.8481,144.9499,Southern Metropolitan,3280,"-37.8481, 144.9499"
85,85,Albert Park,104 Richardson St,4,h,2300000.0,S,Marshall,7/05/2016,3.3,...,1,153.0,180.0,1880,Port Phillip,-37.8447,144.9523,Southern Metropolitan,3280,"-37.8447, 144.9523"
88,88,Albert Park,29 Faussett St,2,h,2120000.0,S,Greg,10/09/2016,3.3,...,1,199.0,107.0,1900,Port Phillip,-37.8422,144.9554,Southern Metropolitan,3280,"-37.8422, 144.9554"
92,92,Albert Park,2 Dundas Pl,3,h,2615000.0,S,Cayzer,10/12/2016,3.3,...,1,177.0,181.0,1880,Port Phillip,-37.8415,144.9585,Southern Metropolitan,3280,"-37.8415, 144.9585"
93,93,Albert Park,23 Finlay St,5,h,2100000.0,S,Greg,10/12/2016,3.3,...,1,237.0,126.0,1970,Port Phillip,-37.8436,144.9557,Southern Metropolitan,3280,"-37.8436, 144.9557"

In [33]:
# Найдём количество зданий с тремя комнатами. Для этого отфильтруем таблицу по условию: 
# обратимся к результирующей таблице по столбцу Rooms и найдём число строк в ней с помощью атрибута shape:

display(melb_data[melb_data['Rooms'] == 3].shape[0])

# Усложним прошлый пример и найдём число трёхкомнатных домов с ценой менее 300 тысяч:

display(melb_data[(melb_data['Rooms'] == 3) & (melb_data['Price'] < 300000)].shape[0])
# 3
# Таких зданий оказалось всего три. Немного «ослабим» условие: теперь нас будут интересовать дома с ценой менее 300 тысяч,
# у которых либо число комнат равно 3 либо площадь домов более 100 квадратных метров:

display(melb_data[((melb_data['Rooms'] == 3) | (melb_data['BuildingArea'] > 100)) & (melb_data['Price'] < 300000)].shape[0])
# 68

5881

3

68

In [34]:
# Фильтрацию часто сочетают со статистическими методами. Давайте найдём максимальное количество комнат в таунхаусах. Так как в результате фильтрации получается DataFrame, то обратимся к нему по столбцу Rooms и найдём максимальное значение:

display(melb_data[melb_data['Type'] == 't']['Rooms'].max())
# 5
# А теперь более сложный трюк: найдём медианную площадь здания у объектов, чья цена выше средней. Для того чтобы оградить наш код от нагромождений, предварительно создадим переменную со средней ценой:

mean_price = melb_data['Price'].mean()
melb_data[melb_data['Price'] > mean_price]['BuildingArea'].median()

np.int64(5)

np.float64(126.0)

In [35]:
# У скольких объектов недвижимости из таблицы melb_data отсутствуют ванные комнаты?
display(melb_data[melb_data['Bathroom'] == 0].shape[0])

34

In [36]:
# Сколько в таблице melb_data объектов недвижимости, которые были проданы риелторской компанией Nelson 
# и стоимость которых составила больше 3 миллионов?
display(melb_data[(melb_data['SellerG'] == 'Nelson') & (melb_data['Price'] > 3000000)].shape[0])

5

In [37]:
# Какова минимальная стоимость участка без здания (площадь здания равна 0) в таблице melb_data?
display(melb_data[melb_data['BuildingArea'] == 0]['Price'].min())

np.float64(412500.0)

In [38]:
# Какова средняя цена объектов недвижимости в таблице melb_data с ценой менее одного миллиона, 
# в которых либо количество комнат больше пяти, либо здание моложе 2015 года?
display(melb_data[(melb_data['Price'] < 1000000) & ((melb_data['Rooms'] > 5) | (melb_data['YearBuilt'] > 2015))]['Price'].mean())

np.float64(769238.6363636364)

In [39]:
# В каком районе Мельбурна чаще всего продаются виллы и коттеджи (тип здания — h) с ценой меньше трёх миллионов?
display(melb_data[(melb_data['Type'] == 'h') & (melb_data['Price'] < 3000000)]['Regionname'].mode())

0    Northern Metropolitan
Name: Regionname, dtype: object

In [ ]:
# 0. Повторение — мать учения
# Задание 0.5

simplelist = [19, 242, 14, 152, 142, 1000]
sum(simplelist)/len(simplelist)
# 2. Pandas.Series
# Задание 2.4

import pandas as pd
def create_medications(names, counts):
    medications = pd.Series(index=names, data=counts)
    return medications
def get_percent(medications, name):
    return(medications.loc[name]/sum(medications) * 100)
# 3. Pandas.DataFrame
# Задание 3.5

import pandas as pd
def create_companyDF(income, expenses, years):
    df = pd.DataFrame({
        'Income': income,
        'Expenses': expenses
        },
        index = years
    )
    return df
def get_profit(df, year):
    if year in df.index:
        profit = df.loc[year, 'Income'] - df.loc[year, 'Expenses']
    else:
        profit=None
    return profit
# 5. Знакомимся с данными: недвижимость
# Задание 5.1

melb_data.loc[15, 'Price']
# Задание 5.2

melb_data.loc[90, 'Date']
# Задание 5.3

round(melb_data.loc[3521, 'Landsize'] / melb_data.loc[1690, 'Landsize'])
# 6. Исследование структуры DataFrame
# Задание 6.8

melb_data.describe(include=['object'])
# Задание 6.9

melb_data['Type'].value_counts(normalize=True)
# 7. Статистические методы
# Задание 7.2

melb_data['Propertycount'].max()
# Задание 7.3

round(melb_data['Distance'].std())
# Задание 7.4

building_median = melb_data['BuildingArea'].median() 
building_mean =  melb_data['BuildingArea'].mean()
deviance = abs(building_median - building_mean)/building_mean
print(round(deviance * 100, 2))
# Задание 7.6

melb_data['Bedroom'].mode()
# 8. Фильтрация данных в DataFrame
# Задание 8.1

melb_data[melb_data['Bathroom'] == 0].shape[0]
# Задание 8.2

melb_data[(melb_data['SellerG'] == 'Nelson') & (melb_data['Price'] > 3e6)].shape[0]
# Задание 8.3

melb_data[(melb_data['BuildingArea'] == 0)]['Price'].min()
# Задание 8.4

round(melb_data[(melb_data['Price']<1e6) & ((melb_data['Rooms']>5) | (melb_data['YearBuilt'] > 2015))]['Price'].mean())
# Задание 8.5

melb_data[(melb_data['Type'] == 'h') & (melb_data['Price'] < 3000000)]['Regionname'].mode()

SyntaxError: invalid syntax (329170045.py, line 43)

In [43]:
# Под предобработкой понимаются следующие этапы работы с данными:
# очистка данных от аномальных значений (выбросов);
# работа с пропущенными значениями;
# удаление признаков, которые не несут полезной информации;
# создание новых признаков;
# преобразование признаков и приведение данных к необходимому для анализа и модели формату.

import pandas as pd

melb_data = pd.read_csv('data/melb_data_ps.csv', sep=',')
# melb_data.head()
melb_df = melb_data.copy()
melb_df.head()

,index,Suburb,Address,Rooms,Type,Price,Method,SellerG,Date,Distance,...,Car,Landsize,BuildingArea,YearBuilt,CouncilArea,Lattitude,Longtitude,Regionname,Propertycount,Coordinates
0,0,Abbotsford,85 Turner St,2,h,1480000.0,S,Biggin,3/12/2016,2.5,...,1,202.0,126.0,1970,Yarra,-37.7996,144.9984,Northern Metropolitan,4019,"-37.7996, 144.9984"
1,1,Abbotsford,25 Bloomburg St,2,h,1035000.0,S,Biggin,4/02/2016,2.5,...,0,156.0,79.0,1900,Yarra,-37.8079,144.9934,Northern Metropolitan,4019,"-37.8079, 144.9934"
2,2,Abbotsford,5 Charles St,3,h,1465000.0,SP,Biggin,4/03/2017,2.5,...,0,134.0,150.0,1900,Yarra,-37.8093,144.9944,Northern Metropolitan,4019,"-37.8093, 144.9944"
3,3,Abbotsford,40 Federation La,3,h,850000.0,PI,Biggin,4/03/2017,2.5,...,1,94.0,126.0,1970,Yarra,-37.7969,144.9969,Northern Metropolitan,4019,"-37.7969, 144.9969"
4,4,Abbotsford,55a Park St,4,h,1600000.0,VB,Nelson,4/06/2016,2.5,...,2,120.0,142.0,2014,Yarra,-37.8072,144.9941,Northern Metropolitan,4019,"-37.8072, 144.9941"

In [44]:
melb_df.drop(['index','Coordinates'],axis=1,inplace=True)
melb_df.head()

,Suburb,Address,Rooms,Type,Price,Method,SellerG,Date,Distance,Postcode,...,Bathroom,Car,Landsize,BuildingArea,YearBuilt,CouncilArea,Lattitude,Longtitude,Regionname,Propertycount
0,Abbotsford,85 Turner St,2,h,1480000.0,S,Biggin,3/12/2016,2.5,3067,...,1,1,202.0,126.0,1970,Yarra,-37.7996,144.9984,Northern Metropolitan,4019
1,Abbotsford,25 Bloomburg St,2,h,1035000.0,S,Biggin,4/02/2016,2.5,3067,...,1,0,156.0,79.0,1900,Yarra,-37.8079,144.9934,Northern Metropolitan,4019
2,Abbotsford,5 Charles St,3,h,1465000.0,SP,Biggin,4/03/2017,2.5,3067,...,2,0,134.0,150.0,1900,Yarra,-37.8093,144.9944,Northern Metropolitan,4019
3,Abbotsford,40 Federation La,3,h,850000.0,PI,Biggin,4/03/2017,2.5,3067,...,2,1,94.0,126.0,1970,Yarra,-37.7969,144.9969,Northern Metropolitan,4019
4,Abbotsford,55a Park St,4,h,1600000.0,VB,Nelson,4/06/2016,2.5,3067,...,1,2,120.0,142.0,2014,Yarra,-37.8072,144.9941,Northern Metropolitan,4019

In [45]:
total_rooms = melb_df['Rooms'] + melb_df['Bedroom'] + melb_df['Bathroom']
display(total_rooms)
# А теперь введём признак MeanRoomsArea, который соответствует средней площади одной комнаты для каждого объекта. 
# Для этого разделим площадь здания на полученное ранее общее количество комнат:
melb_df['MeanRoomsArea'] = melb_df['BuildingArea'] / total_rooms
display(melb_df['MeanRoomsArea'])

0         5
1         5
2         8
3         8
4         8
         ..
13575    10
13576     8
13577     8
13578     9
13579     9
Length: 13580, dtype: int64

0        25.200000
1        15.800000
2        18.750000
3        15.750000
4        17.750000
           ...
13575    12.600000
13576    16.625000
13577    15.750000
13578    17.444444
13579    12.444444
Name: MeanRoomsArea, Length: 13580, dtype: float64

In [46]:
# Можно ввести ещё один интересный признак — AreaRatio, коэффициент соотношения площади здания (BuildingArea) 
# и площади участка (Landsize). Для этого разницу двух площадей поделим на их сумму:
diff_area = melb_df['BuildingArea'] - melb_df['Landsize']
sum_area = melb_df['BuildingArea'] + melb_df['Landsize']
melb_df['AreaRatio'] = diff_area/sum_area
display(melb_df['AreaRatio'])
# Рассмотрим три случая, чтобы понять его значение:
# Если рассматриваемые площади равны, то числитель дроби зануляется и коэффициент тоже равен 0.
# Если одна из площадей начинает доминировать над другой, то коэффициент начинает расти в отрицательную сторону, 
# если площадь участка больше площади здания, и в положительную сторону, если наоборот.
# Наконец, в предельном случае, если площадь здания равна 0, то числитель дроби равен знаменателю со знаком минус, 
# а коэффициент равен -1, а если площадь участка равна 0, то числитель дроби равен знаменателю со знаком плюс, 
# а коэффициент равен 1.
# Таким образом, значение в столбце AreaRatio служит своеобразным указателем соотношения площадей объекта недвижимости. 
# Для пустырей — участков без строений — он будет равен -1, для домов без территории — 1, 
# во всех остальных случаях мы можем увидеть, какая площадь больше — здания или участ

0       -0.231707
1       -0.327660
2        0.056338
3        0.145455
4        0.083969
           ...
13575   -0.676093
13576   -0.429185
13577   -0.551601
13578   -0.693060
13579   -0.527426
Name: AreaRatio, Length: 13580, dtype: float64

In [47]:
# проверить что столбец колонка существует 
import pandas as pd

# Напишите функцию delete_columns(df, col=[]), которая удаляет столбцы из DataFrame и возвращает новую таблицу. Если одного из указанных столбцов не существует в таблице, то функция должна возвращать None.

customer_df = pd.DataFrame({
           'number': [0, 1, 2, 3, 4],
            'cust_id': [128, 1201, 9832, 4392, 7472],
            'cust_age': [13, 21, 19, 21, 60],
            'cust_sale': [0, 0, 0.2, 0.15, 0.3],
            'cust_year_birth': [2008, 2000, 2002, 2000, 1961],
            'cust_order': [1400, 14142, 900, 1240, 8430]
        })


def delete_columns(df, col=[]):
    df_copy = df.copy()
    for c in col:
        if c in df_copy.columns:
            df_copy.drop(c, axis=1, inplace = True)
        else:
            return None
    return df_copy

print(delete_columns(customer_df, col=['number','cust_age']).head())

   cust_id  cust_sale  cust_year_birth  cust_order
0      128       0.00             2008        1400
1     1201       0.00             2000       14142
2     9832       0.20             2002         900
3     4392       0.15             2000        1240
4     7472       0.30             1961        8430

In [48]:
countries_df = pd.DataFrame({
    'country': ['Англия', 'Канада', 'США', 'Россия', 'Украина', 'Беларусь', 'Казахстан'],
    'population': [56.29, 38.05, 322.28, 146.24, 45.5, 9.5, 17.04],
    'area': [133396, 9984670, 9826630, 17125191, 603628, 207600, 2724902]
})
# Задан DataFrame countries_df, содержащий следующие столбцы: название страны, население (population) 
# в миллионах человек и площадь страны (area) в квадратных километрах.
# Для каждой страны рассчитайте плотность населения (количество человек на квадратный километр).
# Затем по полученным данным рассчитайте среднее по плотностям населения в указанных странах. Ответ округлите до сотых.

countries_df['density'] = countries_df['population']*1e6/countries_df['area']
print(round(countries_df['density'].mean(),2))

84.93

In [ ]:
# форматом в Pandas является формат datetime, который записывается как YYYY-MM-DD HH: MM: SS, 
# то есть составляющие времени указываются в следующем порядке: год, месяц, день, час, минута, секунда.
# pandas.to_datetime(arg, errors='raise', dayfirst=False, yearfirst=False, utc=False, format=None, 
# exact=<no_default>, unit=None, infer_datetime_format=<no_default>, origin='unix', cache=True)[source]

# Преобразуем столбец Date в формат datetime, передав его в эту функцию:
melb_df['Date'] = pd.to_datetime(melb_df['Date']) #, dayfirst=True)
display(melb_df['Date'])

0       2016-12-03
1       2016-02-04
2       2017-03-04
3       2017-03-04
4       2016-06-04
           ...
13575   2017-08-26
13576   2017-08-26
13577   2017-08-26
13578   2017-08-26
13579   2017-08-26
Name: Date, Length: 13580, dtype: datetime64[ns]

In [50]:
# Тип данных datetime позволяет с помощью специального аксессора dt выделять составляющие времени 
# из каждого элемента столбца, такие как:
# date — дата;
# year, month, day — год, месяц, день;
# time — время;
# hour, minute, second — час, минута, секунда;
# dayofweek — номер дня недели, от 0 до 6, где 0 — понедельник, 6 — воскресенье;
# day_name — название дня недели;
# dayofyear — порядковый день года;
# quarter — квартал (интервал в три месяца).
# Например, обратившись по атрибуту dt.year в столбце Date, мы можем «достать» год продажи и понять, 
# за какой интервал времени (в годах) представлены наши данные, а также на какой год приходится наибольшее число продаж:

years_sold = melb_df['Date'].dt.year
print(years_sold)
print('Min year sold:', years_sold.min())
print('Max year sold:', years_sold.max())
print('Mode year sold:', years_sold.mode()[0])
# Чтобы сохранить стилистику вывода информации о годе продажи и выводить только число, а не Series, 
# мы обращаемся к результату работы метода mode() по индексу 0

0        2016
1        2016
2        2017
3        2017
4        2016
         ...
13575    2017
13576    2017
13577    2017
13578    2017
13579    2017
Name: Date, Length: 13580, dtype: int32
Min year sold: 2016
Max year sold: 2017
Mode year sold: 2017

In [ ]:
# Теперь попробуем понять, на какие месяцы приходится пик продаж объектов недвижимости. 
# Для этого выделим атрибут dt.month и на этот раз занесём результат в столбец MonthSale, 
# а затем найдём относительную частоту продаж для каждого месяца от общего количества продаж 
# — для этого используем метод value_counts() с параметром normalize (вывод в долях):

melb_df['MonthSale'] = melb_df['Date'].dt.month
melb_df['MonthSale'].value_counts(normalize=True).sort_index(ascending=True) # Сортировка по ключу
# melb_df['MonthSale'].value_counts(normalize=True).sort_values(ascending=False) # Сортировка по значению

MonthSale
1     0.000147
2     0.032622
3     0.049926
4     0.069882
5     0.149411
6     0.134757
7     0.145950
8     0.114138
9     0.135862
10    0.040574
11    0.082032
12    0.044698
Name: proportion, dtype: float64

In [52]:
# Часто бывает такая ситуация, что необходимо вычислять интервалы между двумя временными промежутками. 
# Например, можно вычислить, сколько дней прошло с 1 января 2016 года до момента продажи объекта. 
# Для этого можно просто найти разницу между датами продаж и заявленной датой, представленной в формате datetime:

delta_days = melb_df['Date'] - pd.to_datetime('2016-01-01') 
display(delta_days)

0       337 days
1        34 days
2       428 days
3       428 days
4       155 days
          ...
13575   603 days
13576   603 days
13577   603 days
13578   603 days
13579   603 days
Name: Date, Length: 13580, dtype: timedelta64[ns]

In [53]:
# Чтобы превратить количество дней из формата интервала в формат целого числа дней, 
# можно воспользоваться аксессором dt для формата timedelta и извлечь из него атрибут days:

display(delta_days.dt.days)

0        337
1         34
2        428
3        428
4        155
        ...
13575    603
13576    603
13577    603
13578    603
13579    603
Name: Date, Length: 13580, dtype: int64

In [54]:
# Рассмотрим другой пример. Давайте создадим признак возраста объекта недвижимости в годах на момент продажи. 
# Для этого выделим из столбца с датой продажи год и вычтем из него год постройки здания. 
# Результат оформим в виде столбца AgeBuilding:

melb_df['AgeBuilding'] = melb_df['Date'].dt.year - melb_df['YearBuilt']
display(melb_df['AgeBuilding'])

# На самом деле столбец AgeBuilding дублирует информацию столбца YearBuilt, так как, зная год постройки здания, 
# мы автоматически знаем его возраст. Такие признаки не стоит оставлять вместе, поэтому оставим возраст здания, 
# так как он является более наглядным, а год постройки удалим из таблицы:

melb_df = melb_df.drop('YearBuilt', axis=1)

0         46
1        116
2        117
3         47
4          2
        ...
13575     36
13576     22
13577     20
13578     97
13579     97
Name: AgeBuilding, Length: 13580, dtype: int64

In [55]:
# Создайте в таблице melb_df признак WeekdaySale (день недели). Найдите, сколько объектов недвижимости было продано 
# в выходные (суббота и воскресенье), результат занесите в переменную weekend_count. 
# В качестве ответа введите результат вывода переменной weekend_count.
melb_df['WeekdaySale'] = melb_df['Date'].dt.dayofweek
weekend_count = melb_df[melb_df['WeekdaySale']>4].count()
display(weekend_count[0])

C:\Users\Yuri\AppData\Local\Temp\ipykernel_47292\3449482525.py:6: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  display(weekend_count[0])

np.int64(12822)

In [56]:
# Вам представлены данные (в формате csv) об отчётах очевидцев НЛО в США за период с 1930 по 2020 год.

# В данных есть следующие признаки:

# "City" — город, где был замечен НЛО;
# "Colors Reported" — цвет объекта;
# "Shape Reported" — форма объекта;
# "State" — обозначение штата;
# "Time" — время, когда был замечен НЛО (данные отсортированы от старых наблюдений к новым). 
# Прочитайте данные, сделайте преобразование времени к формату datetime и выполните задания ниже.
ufo_data = pd.read_csv('data/ufo.csv', sep=',')
display(ufo_data.head())

                   City Colors Reported Shape Reported State             Time
0                Ithaca             NaN       TRIANGLE    NY   6/1/1930 22:00
1           Willingboro             NaN          OTHER    NJ  6/30/1930 20:00
2               Holyoke             NaN           OVAL    CO  2/15/1931 14:00
3               Abilene             NaN           DISK    KS   6/1/1931 13:00
4  New York Worlds Fair             NaN          LIGHT    NY  4/18/1933 19:00

In [57]:
ufo_data['Date'] = pd.to_datetime(ufo_data['Time'])
display(ufo_data.head())

,City,Colors Reported,Shape Reported,State,Time,Date
0,Ithaca,NaN,TRIANGLE,NY,6/1/1930 22:00,1930-06-01 22:00:00
1,Willingboro,NaN,OTHER,NJ,6/30/1930 20:00,1930-06-30 20:00:00
2,Holyoke,NaN,OVAL,CO,2/15/1931 14:00,1931-02-15 14:00:00
3,Abilene,NaN,DISK,KS,6/1/1931 13:00,1931-06-01 13:00:00
4,New York Worlds Fair,NaN,LIGHT,NY,4/18/1933 19:00,1933-04-18 19:00:00

In [58]:
# Задание 3.4
# В каком году отмечается наибольшее количество случаев наблюдения НЛО в США?
ufo_data['Date'].dt.year.mode()[0]

np.int32(1999)

In [59]:
# Найдите средний интервал времени (в днях) между двумя последовательными случаями наблюдения НЛО в штате Невада (NV).
# Чтобы выделить дату из столбца Time, можно воспользоваться атрибутом datetime date.
# Чтобы вычислить разницу между двумя соседними датами в столбце, примените к нему метод diff().
# Чтобы перевести интервал времени в дни, воспользуйтесь атрибутом timedelta days.
display(ufo_data[ufo_data['State'] == 'NV']['Date'].diff().dt.days.mean())

# ufo_data['delta'] = ufo_data['Date'].diff()
# ufo_data['days'] = ufo_data['delta'].dt.days
# mean_days = ufo_data[ufo_data['State'] == 'NV']['days'].mean()
# display(mean_days)
# ufo_data.head()

np.float64(68.44876325088339)

In [60]:
# В наших данных есть столбец с адресами объектов недвижимости. Проблема этого столбца в том, 
# что в нём слишком большое количество уникальных значений: почти на каждый объект недвижимости 
# в таблице приходится свой уникальный адрес. Убедимся в этом, вычислив количество уникальных значений 
# в столбце с помощью метода nunique():

print(melb_df['Address'].nunique())

13378

In [61]:
# Обычно подобные признаки удаляют, однако можно поступить умнее: давайте извлечём из признака адреса характеристику 
# подтипа улицы (улица, шоссе, авеню, бульвар). Для этого сначала внимательнее посмотрим на структуру адреса, 
# выберем несколько строк столбца Address:

print(melb_df['Address'].loc[177])
print(melb_df['Address'].loc[1812])
print(melb_df['Address'].loc[9001])
# 2/119 Railway St N
# 9/400 Dandenong Rd
# 172 Danks St

2/119 Railway St N
9/400 Dandenong Rd
172 Danks St

In [62]:
# Итак, адрес строится следующим образом: сначала указывается номер дома и корпус, 
# после указывается название улицы, а в конце — подтип улицы, но в некоторых случаях к подтипу добавляется 
# географическая отметка (N — север, S — юг и т. д.), она нам не нужна . Для того чтобы выделить подтип улицы, 
# на которой находится объект, можно использовать следующую функцию:

# На вход данной функции поступает строка с адресом.
def get_street_type(address):
# Создаём список географических пометок exclude_list.
    exclude_list = ['N', 'S', 'W', 'E']
# Метод split() разбивает строку на слова по пробелу.
# В результате получаем список слов в строке и заносим его в переменную address_list.
    address_list = address.split(' ')
# Обрезаем список, оставляя в нём только последний элемент,
# потенциальный подтип улицы, и заносим в переменную street_type.
    street_type = address_list[-1]
# Делаем проверку на то, что полученный подтип является географической пометкой.
# Для этого проверяем его на наличие в списке exclude_list.
    if street_type in exclude_list:
# Если переменная street_type является географической пометкой,
# переопределяем её на второй элемент с конца списка address_list.
        street_type = address_list[-2]
# Возвращаем переменную street_type, в которой хранится подтип улицы.

#  подтипы Av и Avenue, Bvd и Boulevard, Pde и Parade. Мы упустили данный момент
    longs_dict = {'Avenue': 'Av', 'Boulevard': 'Bvd', 'Parade': 'Pde'}
    if street_type in longs_dict.keys():
        street_type = longs_dict[street_type]

    return street_type

street_types = melb_df['Address'].apply(get_street_type)
display(street_types)
print(street_types.nunique())
display(street_types.value_counts())

0        St
1        St
2        St
3        La
4        St
         ..
13575    Cr
13576    Dr
13577    St
13578    St
13579    St
Name: Address, Length: 13580, dtype: object

53

Address
St           8012
Rd           2825
Ct            612
Dr            447
Av            361
Gr            311
Pde           226
Pl            169
Cr            152
Cl            100
La             67
Bvd            66
Tce            47
Wy             40
Cct            25
Hwy            24
Sq             11
Crescent        9
Strand          7
Cir             7
Esplanade       6
Grove           5
Fairway         4
Gdns            4
Mews            4
Grn             4
Crossway        3
Righi           3
Esp             2
Ridge           2
Crofts          2
Victoria        2
Highway         1
Athol           1
Cove            1
Grange          1
Res             1
Terrace         1
Qy              1
Glade           1
Nook            1
Dell            1
Eyrie           1
East            1
Loop            1
Grand           1
Gra             1
Summit          1
Hts             1
Outlook         1
Woodland        1
Ave             1
Corso           1
Name: count, dtype: int64

In [ ]:
# В таком случае давайте применим очень распространённый метод уменьшения количества уникальных категорий 
# — выделим n подтипов, которые встречаются чаще всего, а остальные обозначим как 'other' (другие).
# Для этого к результату метода value_counts применим метод nlargest(), 
# который возвращает n наибольших значений из Series. Зададим n=10, 
# т. е. мы хотим отобрать десять наиболее популярных подтипов. Извлечём их названия с помощью атрибута index, 
# а результат занесём в переменную popular_stypes:

popular_stypes = street_types.value_counts().nlargest(10).index
print(popular_stypes)
# Index(['St', 'Rd', 'Ct', 'Dr', 'Av', 'Gr', 'Pde', 'Pl', 'Cr', 'Cl'], dtype='object')

# Теперь, когда у нас есть список наиболее популярных подтипов улиц, введём lambda-функцию, 
# которая будет проверять, есть ли строка x в этом перечне, и, если это так, lambda-функция будет возвращать x, 
# в противном случае она будет возвращать строку 'other'. Наконец, применим такую функцию к Series street_types, 
# полученной ранее, а результат определим в новый столбец таблицы StreetType:

melb_df['StreetType'] = street_types.apply(lambda x: x if x in popular_stypes else 'other')
display(melb_df['StreetType'])

print(melb_df['StreetType'].nunique())

Index(['St', 'Rd', 'Ct', 'Dr', 'Av', 'Gr', 'Pde', 'Pl', 'Cr', 'Cl'], dtype='object', name='Address')

0           St
1           St
2           St
3        other
4           St
         ...
13575       Cr
13576       Dr
13577       St
13578       St
13579       St
Name: StreetType, Length: 13580, dtype: object

11

In [64]:

# Теперь, у нас нет потребности хранить признак Address, так как, если конкретное местоположение объекта всё же 
# и влияет на его стоимость, то оно определяется столбцами Longitude и Lattitude. Удалим его из нашей таблицы:

# melb_df = melb_df.drop('Address', axis=1)
melb_df['StreetType'].value_counts()

StreetType
St       8012
Rd       2825
Ct        612
Dr        447
other     365
Av        361
Gr        311
Pde       226
Pl        169
Cr        152
Cl        100
Name: count, dtype: int64

In [66]:
# Напишите функцию get_weekend(weekday), которая принимает на вход элемент столбца WeekdaySale и возвращает 1, 
# если день является выходным, и 0 — в противном случае, и создайте столбец Weekend в таблице melb_df с помощью неё.
# Примените эту функцию к столбцу и вычислите среднюю цену объекта недвижимости, проданного в выходные дни. 
# Результат округлите до целых.

def get_weekend(weekday):
    if weekday > 4:
        return 1
    else:
        return 0
    
melb_df['Weekend'] = melb_df['WeekdaySale'].apply(get_weekend)
display(melb_df[melb_df['Weekend'] == 1]['Price'].mean())
melb_df.head()

np.float64(1081198.6406956792)

,Suburb,Address,Rooms,Type,Price,Method,SellerG,Date,Distance,Postcode,...,Longtitude,Regionname,Propertycount,MeanRoomsArea,AreaRatio,MonthSale,AgeBuilding,WeekdaySale,StreetType,Weekend
0,Abbotsford,85 Turner St,2,h,1480000.0,S,Biggin,2016-12-03,2.5,3067,...,144.9984,Northern Metropolitan,4019,25.20,-0.231707,12,46,5,St,1
1,Abbotsford,25 Bloomburg St,2,h,1035000.0,S,Biggin,2016-02-04,2.5,3067,...,144.9934,Northern Metropolitan,4019,15.80,-0.327660,2,116,3,St,0
2,Abbotsford,5 Charles St,3,h,1465000.0,SP,Biggin,2017-03-04,2.5,3067,...,144.9944,Northern Metropolitan,4019,18.75,0.056338,3,117,5,St,1
3,Abbotsford,40 Federation La,3,h,850000.0,PI,Biggin,2017-03-04,2.5,3067,...,144.9969,Northern Metropolitan,4019,15.75,0.145455,3,47,5,other,1
4,Abbotsford,55a Park St,4,h,1600000.0,VB,Nelson,2016-06-04,2.5,3067,...,144.9941,Northern Metropolitan,4019,17.75,0.083969,6,2,5,St,1

In [76]:
# Преобразуйте столбец SellerG с наименованиями риелторских компаний в таблице melb_df следующим образом: 
# оставьте в столбце только 49 самых популярных компаний, а остальные обозначьте как 'other'.
# Найдите, во сколько раз минимальная цена объектов недвижимости, проданных компанией 'Nelson', 
# больше минимальной цены объектов, проданных компаниями, обозначенными как 'other'. Ответ округлите до десятых.

popular_SellerG = melb_df['SellerG'].value_counts().nlargest(49).index
# display(popular_SellerG)
melb_df['SellerG'] = melb_df['SellerG'].apply(lambda x: x if x in popular_SellerG else 'other')
Nelson_min = melb_df[melb_df['SellerG']=='Nelson']['Price'].min()
other_min = melb_df[melb_df['SellerG']=='other']['Price'].min()
display(round(Nelson_min/other_min, 1))

np.float64(1.3)

In [ ]:
# Представьте, что вы занимаетесь подготовкой данных о вакансиях с платформы hh.ru. 
# В вашем распоряжении имеется таблица, в которой с помощью парсинга собраны резюме кандидатов. 
# В этой таблице есть текстовый столбец «Опыт работы». Пример такого столбца представлен ниже в виде объекта Series. 
# Структура текста в столбце фиксирована и не может измениться.
# Напишите функцию get_experience(arg), аргументом которой является строка столбца с опытом работы. 
# Функция должна возвращать опыт работы в месяцах. Не забудьте привести результат к целому числу.
# Примечание. Обратите внимание, что опыт работы может выражаться только в годах или только в месяцах. 
# Учтите это при построении своей функции.
# При проверке мы будем применять вашу функцию к разным Series с помощью метода apply().
def get_experience(arg):
    # Убираем слово "Опыт работы" и лишние пробелы
    text = arg.replace("Опыт работы", "").strip()
    
    years = 0
    months = 0

    # Если в тексте есть слово "год" или "лет" — извлекаем число перед ним
    if "год" in text:
        parts = text.split("год")[0].strip().split()
        years = int(parts[-1])  # последнее число перед словом "год"
    elif "лет" in text:
        parts = text.split("лет")[0].strip().split()
        years = int(parts[-1])  # последнее число перед словом "год"
    
    # Если есть слово "месяц" — извлекаем число перед ним
    if "месяц" in text:
        parts = text.split("месяц")[0].strip().split()
        months = int(parts[-1])  # последнее число перед словом "месяц"
    
    # Возвращаем общее количество месяцев
    return years * 12 + months

In [77]:
# создаём пустой список
unique_list = []
# пробегаемся по именам столбцов в таблице
for col in melb_df.columns:
    # создаём кортеж (имя столбца, число уникальных значений)
    item = (col, melb_df[col].nunique(),melb_df[col].dtypes) 
    # добавляем кортеж в список
    unique_list.append(item) 
# создаём вспомогательную таблицу и сортируем её
unique_counts = pd.DataFrame(
    unique_list,
    columns=['Column_Name', 'Num_Unique', 'Type']
).sort_values(by='Num_Unique',  ignore_index=True)
# выводим её на экран
display(unique_counts)

      Column_Name  Num_Unique            Type
0         Weekend           2           int64
1            Type           3          object
2     WeekdaySale           5           int32
3          Method           5          object
4      Regionname           8          object
5           Rooms           9           int64
6        Bathroom           9           int64
7             Car          11           int64
8      StreetType          11          object
9         Bedroom          12           int64
10      MonthSale          12           int32
11    CouncilArea          33          object
12        SellerG          49          object
13           Date          58  datetime64[ns]
14    AgeBuilding         152           int64
15       Postcode         198           int64
16       Distance         202         float64
17  Propertycount         311           int64
18         Suburb         314          object
19   BuildingArea         602         float64
20  MeanRoomsArea        1277         float64
21       Landsize        1448         float64
22          Price        2204         float64
23      Lattitude        6503         float64
24      AreaRatio        6521         float64
25     Longtitude        7063         float64
26        Address       13378          object

In [78]:
# Сделаем преобразование столбцов к типу данных category:

cols_to_exclude = ['Date', 'Rooms', 'Bedroom', 'Bathroom', 'Car'] # список столбцов, которые мы не берём во внимание
max_unique_count = 150 # задаём максимальное число уникальных категорий
for col in melb_df.columns: # цикл по именам столбцов
    if melb_df[col].nunique() < max_unique_count and col not in cols_to_exclude: # проверяем условие
        melb_df[col] = melb_df[col].astype('category') # преобразуем тип столбца
display(melb_df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13580 entries, 0 to 13579
Data columns (total 27 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Suburb         13580 non-null  object
 1   Address        13580 non-null  object
 2   Rooms          13580 non-null  int64
 3   Type           13580 non-null  category
 4   Price          13580 non-null  float64
 5   Method         13580 non-null  category
 6   SellerG        13580 non-null  category
 7   Date           13580 non-null  datetime64[ns]
 8   Distance       13580 non-null  float64
 9   Postcode       13580 non-null  int64
 10  Bedroom        13580 non-null  int64
 11  Bathroom       13580 non-null  int64
 12  Car            13580 non-null  int64
 13  Landsize       13580 non-null  float64
 14  BuildingArea   13580 non-null  float64
 15  CouncilArea    12211 non-null  category
 16  Lattitude      13580 non-null  float64
 17  Longtitude     13580 non-null  float64
 18  Regionname     13580 non-null  category
 19  Propertycount  13580 non-null  int64
 20  MeanRoomsArea  13580 non-null  float64
 21  AreaRatio      13580 non-null  float64
 22  MonthSale      13580 non-null  category
 23  AgeBuilding    13580 non-null  int64
 24  WeekdaySale    13580 non-null  category
 25  StreetType     13580 non-null  category
 26  Weekend        13580 non-null  category
dtypes: category(9), datetime64[ns](1), float64(8), int64(7), object(2)
memory usage: 2.0+ MB

None

In [80]:
print(melb_df['Regionname'].cat.categories)
display(melb_df['Regionname'].cat.codes)

Index(['Eastern Metropolitan', 'Eastern Victoria', 'Northern Metropolitan',
       'Northern Victoria', 'South-Eastern Metropolitan',
       'Southern Metropolitan', 'Western Metropolitan', 'Western Victoria'],
      dtype='object')

0        2
1        2
2        2
3        2
4        2
        ..
13575    4
13576    6
13577    6
13578    6
13579    6
Length: 13580, dtype: int8

In [81]:
melb_df['Type'] = melb_df['Type'].cat.rename_categories({
    'u': 'unit',
    't': 'townhouse',
    'h': 'house'
})
display(melb_df['Type'])

0        house
1        house
2        house
3        house
4        house
         ...
13575    house
13576    house
13577    house
13578    house
13579    house
Name: Type, Length: 13580, dtype: category
Categories (3, object): ['house', 'townhouse', 'unit']

In [ ]:

# new_houses_types = pd.Series(['unit', 'house', 'flat', 'flat', 'house'])
# new_houses_types = new_houses_types.astype(melb_df['Type'].dtype)
# display(new_houses_types)

# С нашими новыми объектами недвижимости произошло нечто странное. 
# По какой-то причине вместо квартир мы получили пустые значения — NaN.
# На самом деле причина проста: тип данных category хранит только категории, 
# которые были объявлены при его инициализации. При встрече с новой, неизвестной ранее категорией, 
# этот тип превратит её в пустое значение, так как он просто не знает о существовании этой категории.
# Решить эту проблему на самом деле не сложно. Можно добавить категорию flat в столбец Type 
# с помощью метода акссесора cat add_categories(), в который достаточно просто передать имя новой категории:

melb_df['Type'] = melb_df['Type'].cat.add_categories('flat')
new_houses_types = pd.Series(['unit', 'house', 'flat', 'flat', 'house'])
new_houses_types = new_houses_types.astype(melb_df['Type'].dtype)
display(new_houses_types)

In [86]:
# При преобразовании столбцов таблицы о недвижимости к типу category мы оставили без внимания столбец Suburb (пригород). 
# Давайте исправим это.
# С помощью метода info() узнайте, сколько памяти занимает таблица melb_df.
# Преобразуйте признак Suburb следующим образом: оставьте в столбце только 119 наиболее популярных пригородов, 
# остальные замените на 'other'.
# Приведите данные в столбце Suburb к категориальному типу.
# В качестве ответа запишите разницу между объёмом занимаемой памяти до преобразования 
# (который мы получили ранее в модуле) и после него в Мб. Ответ округлите до десятых.

melb_df.info()

popular_Suburb = melb_df['Suburb'].value_counts().nlargest(119).index
# display(popular_Suburb)
melb_df['Suburb'] = melb_df['Suburb'].apply(lambda x: x if x in popular_Suburb else 'other')
melb_df['Suburb'] = melb_df['Suburb'].astype('category') # преобразуем тип столбца
display(melb_df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13580 entries, 0 to 13579
Data columns (total 27 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Suburb         13580 non-null  category
 1   Address        13580 non-null  object
 2   Rooms          13580 non-null  int64
 3   Type           13580 non-null  category
 4   Price          13580 non-null  float64
 5   Method         13580 non-null  category
 6   SellerG        13580 non-null  category
 7   Date           13580 non-null  datetime64[ns]
 8   Distance       13580 non-null  float64
 9   Postcode       13580 non-null  int64
 10  Bedroom        13580 non-null  int64
 11  Bathroom       13580 non-null  int64
 12  Car            13580 non-null  int64
 13  Landsize       13580 non-null  float64
 14  BuildingArea   13580 non-null  float64
 15  CouncilArea    12211 non-null  category
 16  Lattitude      13580 non-null  float64
 17  Longtitude     13580 non-null  float64
 18  Regionname     13580 non-null  category
 19  Propertycount  13580 non-null  int64
 20  MeanRoomsArea  13580 non-null  float64
 21  AreaRatio      13580 non-null  float64
 22  MonthSale      13580 non-null  category
 23  AgeBuilding    13580 non-null  int64
 24  WeekdaySale    13580 non-null  category
 25  StreetType     13580 non-null  category
 26  Weekend        13580 non-null  category
dtypes: category(10), datetime64[ns](1), float64(8), int64(7), object(1)
memory usage: 1.9+ MB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13580 entries, 0 to 13579
Data columns (total 27 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Suburb         13580 non-null  category
 1   Address        13580 non-null  object
 2   Rooms          13580 non-null  int64
 3   Type           13580 non-null  category
 4   Price          13580 non-null  float64
 5   Method         13580 non-null  category
 6   SellerG        13580 non-null  category
 7   Date           13580 non-null  datetime64[ns]
 8   Distance       13580 non-null  float64
 9   Postcode       13580 non-null  int64
 10  Bedroom        13580 non-null  int64
 11  Bathroom       13580 non-null  int64
 12  Car            13580 non-null  int64
 13  Landsize       13580 non-null  float64
 14  BuildingArea   13580 non-null  float64
 15  CouncilArea    12211 non-null  category
 16  Lattitude      13580 non-null  float64
 17  Longtitude     13580 non-null  float64
 18  Regionname     13580 non-null  category
 19  Propertycount  13580 non-null  int64
 20  MeanRoomsArea  13580 non-null  float64
 21  AreaRatio      13580 non-null  float64
 22  MonthSale      13580 non-null  category
 23  AgeBuilding    13580 non-null  int64
 24  WeekdaySale    13580 non-null  category
 25  StreetType     13580 non-null  category
 26  Weekend        13580 non-null  category
dtypes: category(10), datetime64[ns](1), float64(8), int64(7), object(1)
memory usage: 1.9+ MB

None

In [87]:
# Вашим заданием в этом модуле будет проанализировать и преобразовать данные о велопоездках клиентов компании Citi Bike 
# (США), специализирующейся на прокате велосипедов.
# Датасет представляет собой таблицу с информацией о 300 тысячах поездок за первые пять дней сентября 2018 года 
# и включает в себя следующую информацию:

# starttime — время начала поездки (дата, время);
# stoptime — время окончания поездки (дата, время);
# start station id — идентификатор стартовой стоянки;
# start station name — название стартовой стоянки;
# start station latitude, start station longitude — географическая широта и долгота стартовой стоянки;
# end station id — идентификатор конечной стоянки;
# end station name — название конечной стоянки;
# end station latitude, end station longitude — географическая широта и долгота конечной стоянки;
# bikeid — идентификатор велосипеда;
# usertype — тип пользователя (Customer — клиент с подпиской на 24 часа или на три дня, Subscriber — подписчик 
#            с годовой арендой велосипеда);
# birth year — год рождения клиента;
# gender — пол клиента (0 — неизвестный, 1 — мужчина, 2 — женщина).

import pandas as pd

bikes_data = pd.read_csv('data/citibike-tripdata.csv', sep=',')
# melb_data.head()
bikes_d = bikes_data.copy()
bikes_d.head()

,starttime,stoptime,start station id,start station name,start station latitude,start station longitude,end station id,end station name,end station latitude,end station longitude,bikeid,usertype,birth year,gender
0,2018-09-01 00:00:05.2690,2018-09-01 00:27:20.6340,252.0,MacDougal St & Washington Sq,40.732264,-73.998522,366.0,Clinton Ave & Myrtle Ave,40.693261,-73.968896,25577,Subscriber,1980,1
1,2018-09-01 00:00:11.2810,2018-09-01 00:02:23.4810,314.0,Cadman Plaza West & Montague St,40.693830,-73.990539,3242.0,Schermerhorn St & Court St,40.691029,-73.991834,34377,Subscriber,1969,0
2,2018-09-01 00:00:20.6490,2018-09-01 00:55:58.5470,3142.0,1 Ave & E 62 St,40.761227,-73.960940,3384.0,Smith St & 3 St,40.678724,-73.995991,30496,Subscriber,1975,1
3,2018-09-01 00:00:21.7460,2018-09-01 00:07:38.5830,308.0,St James Pl & Oliver St,40.713079,-73.998512,3690.0,Park Pl & Church St,40.713342,-74.009355,28866,Subscriber,1984,2
4,2018-09-01 00:00:27.3150,2018-09-01 02:21:25.3080,345.0,W 13 St & 6 Ave,40.736494,-73.997044,380.0,W 4 St & 7 Ave S,40.734011,-74.002939,20943,Customer,1994,1

In [88]:
bikes_d.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 300000 entries, 0 to 299999
Data columns (total 14 columns):
 #   Column                   Non-Null Count   Dtype
---  ------                   --------------   -----
 0   starttime                300000 non-null  object
 1   stoptime                 300000 non-null  object
 2   start station id         299831 non-null  float64
 3   start station name       299831 non-null  object
 4   start station latitude   300000 non-null  float64
 5   start station longitude  300000 non-null  float64
 6   end station id           299831 non-null  float64
 7   end station name         299831 non-null  object
 8   end station latitude     300000 non-null  float64
 9   end station longitude    300000 non-null  float64
 10  bikeid                   300000 non-null  int64
 11  usertype                 300000 non-null  object
 12  birth year               300000 non-null  int64
 13  gender                   300000 non-null  int64
dtypes: float64(6), int64(3), object(5)
memory usage: 32.0+ MB

In [91]:
# Сколько пропусков в столбце start station id?
display(bikes_d['start station id'].isna().sum())
display(bikes_d['start station id'].isnull().sum())

np.int64(169)

np.int64(169)

In [98]:
# Найдите идентификатор самой популярной стартовой стоянки. Запишите идентификатор в виде целого числа.
display(bikes_d['start station id'].value_counts().nlargest(15))

start station id
281.0     1928
2006.0    1909
519.0     1873
514.0     1845
426.0     1835
497.0     1727
499.0     1639
3002.0    1623
435.0     1612
402.0     1601
285.0     1595
387.0     1464
3256.0    1413
457.0     1401
382.0     1391
Name: count, dtype: int64

In [99]:
# Велосипед с каким идентификатором является самым популярным?
display(bikes_d['bikeid'].value_counts().nlargest(15))

bikeid
33887    107
34358    104
34159    103
34258    103
34314    102
34332    102
33916    102
34730    102
34328    102
34785    101
34226    101
34199    100
34168     99
34009     99
34308     99
Name: count, dtype: int64

In [104]:
# Какой тип клиентов (столбец usertype) является преобладающим — Subscriber или Customer? 
# В качестве ответа запишите долю клиентов преобладающего типа среди общего количества клиентов. Ответ округлите до сотых.
bikes_d['usertype'].value_counts(normalize=True).sort_values(ascending=False)

usertype
Subscriber    0.774007
Customer      0.225993
Name: proportion, dtype: float64

In [103]:
# Кто больше занимается велоспортом — мужчины или женщины? 
# В ответ запишите число поездок для той группы, у которой их больше.
bikes_d['gender'].value_counts(normalize=False).sort_values(ascending=False)

gender
1    183582
2     74506
0     41912
Name: count, dtype: int64

In [107]:
# Число уникальных стартовых и конечных стоянок, которыми воспользовались клиенты, не равны друг другу?
display(bikes_d['start station id'].nunique())
display(bikes_d['end station id'].nunique())

759

765

In [ ]:
# В рассматриваемые дни минимальный возраст клиента составлял 10 лет?
# Датасет представляет собой таблицу с информацией о 300 тысячах поездок за первые пять дней сентября 2018 года
display(bikes_d['birth year'].max())

np.int64(2002)

In [112]:
# Самой непопулярной стартовой стоянкой из тех, которыми воспользовались клиенты, 
# является стоянка с названием "Eastern Pkwy & Washington Ave"
display(bikes_d['start station name'].value_counts(normalize=False).sort_values(ascending=False))

start station name
Grand Army Plaza & Central Park S    1928
Central Park S & 6 Ave               1909
Pershing Square North                1873
12 Ave & W 40 St                     1845
West St & Chambers St                1835
                                     ...
NYCBS Depot - GOW                      15
Franklin Ave & Empire Blvd             11
Railroad Ave & Kay Ave                  9
47 Ave & Skillman Ave                   7
Eastern Pkwy & Washington Ave           6
Name: count, Length: 759, dtype: int64

In [113]:
# Наибольшее количество поездок завершается на стоянке под названием "Liberty Light Rail"
display(bikes_d['end station name'].value_counts(normalize=False).sort_values(ascending=False))

end station name
West St & Chambers St          1963
12 Ave & W 40 St               1909
Pershing Square North          1850
Central Park S & 6 Ave         1828
E 17 St & Broadway             1804
                               ...
Exchange Place                    3
Union St                          1
Montrose Ave & Bushwick Ave       1
Warren St                         1
Liberty Light Rail                1
Name: count, Length: 765, dtype: int64

In [117]:
# В наших данных присутствуют столбцы, которые дублируют информацию друг о друге: 
# это столбцы с идентификатором и названием стартовой и конечной стоянки. Удалите признаки идентификаторов стоянок. 
# Сколько столбцов осталось?

bikes_dropted = bikes_d.drop(['start station id','end station id'],axis=1) #,inplace=True)
display(bikes_dropted.columns.shape[0])

bikes_d.drop(['start station id','end station id'],axis=1,inplace=True)
display(bikes_d.columns.shape[0])

12

12

In [120]:
# Замените признак birth year на более понятный признак возраста клиента age. 
# Годом отсчёта возраста выберите 2018 год. Столбец birth year удалите из таблицы. 
# Сколько поездок совершено клиентами старше 60 лет?
bikes_d['age'] = 2018 - bikes_d['birth year']
bikes_d.drop(['birth year'],axis=1,inplace=True)
bikes_d[bikes_d['age'] > 60].count()

starttime                  11837
stoptime                   11837
start station name         11837
start station latitude     11837
start station longitude    11837
end station name           11837
end station latitude       11837
end station longitude      11837
bikeid                     11837
usertype                   11837
gender                     11837
age                        11837
dtype: int64

In [123]:
# Создайте признак длительности поездки trip duration. 
# Для этого вычислите интервал времени между временем окончания поездки (stoptime) и её началом (starttime). 
# Сколько целых минут длилась поездка под индексом 3 в таблице?
bikes_d['trip duration'] = pd.to_datetime(bikes_d['stoptime']) - pd.to_datetime(bikes_d['starttime'])
display(bikes_d['trip duration'])

0        0 days 00:27:15.365000
1        0 days 00:02:12.200000
2        0 days 00:55:37.898000
3        0 days 00:07:16.837000
4        0 days 02:20:57.993000
                  ...
299995   0 days 00:07:23.648000
299996   0 days 00:11:33.138000
299997   0 days 00:05:12.997000
299998   0 days 00:56:00.092000
299999   0 days 00:03:45.051000
Name: trip duration, Length: 300000, dtype: timedelta64[ns]

In [ ]:
# 2. Базовые операции со столбцами DataFrame
# Задание 2.3

def delete_columns(df, col=[]):
    for cc in col:
        if cc not in df.columns:
            return None
    return df.drop(col, axis=1)
# Задание 2.4

countries_df = pd.DataFrame({
    'country': ['Англия', 'Канада', 'США', 'Россия', 'Украина', 'Беларусь', 'Казахстан'],
    'population': [56.29, 38.05, 322.28, 146.24, 45.5, 9.5, 17.04],
    'square': [133396, 9984670, 9826630, 17125191, 603628, 207600, 2724902]
})
countries_df['density'] = countries_df['population'] / countries_df['square'] * 1e6
print(round(countries_df['density'].mean(), 2))
# 3. Работа с датами в DataFrame
# Задание 3.3

melb_df['WeekdaySale'] = melb_df['Date'].dt.dayofweek
weekend_count = melb_df[(melb_df['WeekdaySale'] == 5) | (melb_df['WeekdaySale'] == 6)].shape[0]
print(weekend_count)
# Задание 3.4

df = pd.read_csv('http://bit.ly/uforeports')
df['Time'] = pd.to_datetime(df.Time)
print(df['Time'].dt.year.mode()[0])
# Задание 3.5

df['Date'] = df['Time'].dt.date
print(df[df['State']=='NV']['Date'].diff().dt.days.mean())
# 4. Создание и преобразование столбцов с помощью функций
# Задание 4.2

def get_weekend(weekday):
    if weekday == 5 or weekday == 6:
        return 1
    else: 
        return 0
melb_df['Weekend'] = melb_df['WeekdaySale'].apply(get_weekend)
print(round(melb_df[melb_df['Weekend']==1]['Price'].mean(), 2))
# Задание 4.3

popular_seller = melb_df['SellerG'].value_counts().nlargest(49).index
# заменяем имена компаний, не попавших в список популярных, на строку 'other'
melb_df['SellerG'] = melb_df['SellerG'].apply(lambda x: x if x in popular_seller else 'other') 

a = melb_df[melb_df['SellerG'] == 'Nelson']['Price'].min()
b = melb_df[melb_df['SellerG'] == 'other']['Price'].min()
print(round(a/b, 1))

# Задание 4.4

def get_experience(arg):
    month_key_words = ['месяц', 'месяцев', 'месяца']
    year_key_words = ['год', 'лет', 'года']
    args_splited = arg.split(' ')
    month = 0
    year = 0
    for i in range(len(args_splited)):
        if args_splited[i] in month_key_words:
            month = args_splited[i-1]
        if args_splited[i] in year_key_words:
            year = args_splited[i-1]
    return int(year)*12 + int(month)