In [46]:
import pandas as pd

melb_df_orig = pd.read_csv('data/melb_data_fe.csv')
melb_df = melb_df_orig.copy()
melb_df.head()

,Suburb,Rooms,Type,Price,Method,SellerG,Date,Distance,Postcode,Bedroom,...,Longtitude,Regionname,Propertycount,MeanRoomsSquare,AreaRatio,MonthSale,AgeBuilding,WeekdaySale,StreetType,Weekend
0,Abbotsford,2,house,1480000.0,S,Biggin,2016-03-12,2.5,3067,2,...,144.9984,Northern Metropolitan,4019,25.20,-0.231707,3,46,5,St,1
1,Abbotsford,2,house,1035000.0,S,Biggin,2016-04-02,2.5,3067,2,...,144.9934,Northern Metropolitan,4019,15.80,-0.327660,4,116,5,St,1
2,Abbotsford,3,house,1465000.0,SP,Biggin,2017-04-03,2.5,3067,3,...,144.9944,Northern Metropolitan,4019,18.75,0.056338,4,117,0,St,0
3,Abbotsford,3,house,850000.0,PI,Biggin,2017-04-03,2.5,3067,3,...,144.9969,Northern Metropolitan,4019,15.75,0.145455,4,47,0,other,0
4,Abbotsford,4,house,1600000.0,VB,Nelson,2016-04-06,2.5,3067,3,...,144.9941,Northern Metropolitan,4019,17.75,0.083969,4,2,2,St,0

In [47]:
display(melb_df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13580 entries, 0 to 13579
Data columns (total 26 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Suburb           13580 non-null  object
 1   Rooms            13580 non-null  int64
 2   Type             13580 non-null  object
 3   Price            13580 non-null  float64
 4   Method           13580 non-null  object
 5   SellerG          13580 non-null  object
 6   Date             13580 non-null  object
 7   Distance         13580 non-null  float64
 8   Postcode         13580 non-null  int64
 9   Bedroom          13580 non-null  int64
 10  Bathroom         13580 non-null  int64
 11  Car              13580 non-null  int64
 12  Landsize         13580 non-null  float64
 13  BuildingArea     13580 non-null  float64
 14  CouncilArea      12211 non-null  object
 15  Lattitude        13580 non-null  float64
 16  Longtitude       13580 non-null  float64
 17  Regionname       13580 non-null  object
 18  Propertycount    13580 non-null  int64
 19  MeanRoomsSquare  13580 non-null  float64
 20  AreaRatio        13580 non-null  float64
 21  MonthSale        13580 non-null  int64
 22  AgeBuilding      13580 non-null  int64
 23  WeekdaySale      13580 non-null  int64
 24  StreetType       13580 non-null  object
 25  Weekend          13580 non-null  int64
dtypes: float64(8), int64(10), object(8)
memory usage: 2.7+ MB

None

In [48]:
# Преобразуйте столбец Date в формат datetime
melb_df['Date'] = pd.to_datetime(melb_df['Date'])
display(melb_df['Date'])

0       2016-03-12
1       2016-04-02
2       2017-04-03
3       2017-04-03
4       2016-04-06
           ...
13575   2017-08-26
13576   2017-08-26
13577   2017-08-26
13578   2017-08-26
13579   2017-08-26
Name: Date, Length: 13580, dtype: datetime64[ns]

In [49]:
# выделите квартал (quarter) продажи объектов недвижимости. Найдите второй по популярности квартал продажи. 
# В качестве ответа запишите число объектов, проданных в этом квартале.
# melb_df['quarter'] = melb_df['Date'].dt.quarter
# melb_df['quarter'].value_counts().nlargest()

# Похоже по следующему заданиб создавать не надо было, поэтому
melb_df['Date'].dt.quarter.value_counts().nlargest()

Date
3    4873
2    4359
4    2329
1    2019
Name: count, dtype: int64

In [51]:
# Преобразуйте все столбцы, в которых меньше 150 уникальных значений, в тип данных category, 
# исключив из преобразования столбцы Date, Rooms, Bedroom, Bathroom, Car.

cols_to_exclude = ['Date', 'Rooms', 'Bedroom', 'Bathroom', 'Car'] # список столбцов, которые мы не берём во внимание
max_unique_count = 150 # задаём максимальное число уникальных категорий
for col in melb_df.columns: # цикл по именам столбцов
    if melb_df[col].nunique() < max_unique_count and col not in cols_to_exclude: # проверяем условие
        melb_df[col] = melb_df[col].astype('category') # преобразуем тип столбца
display(melb_df.info())

count_cat = melb_df.select_dtypes(include='category').columns
print(count_cat)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13580 entries, 0 to 13579
Data columns (total 26 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Suburb           13580 non-null  category
 1   Rooms            13580 non-null  int64
 2   Type             13580 non-null  category
 3   Price            13580 non-null  float64
 4   Method           13580 non-null  category
 5   SellerG          13580 non-null  category
 6   Date             13580 non-null  datetime64[ns]
 7   Distance         13580 non-null  float64
 8   Postcode         13580 non-null  int64
 9   Bedroom          13580 non-null  int64
 10  Bathroom         13580 non-null  int64
 11  Car              13580 non-null  int64
 12  Landsize         13580 non-null  float64
 13  BuildingArea     13580 non-null  float64
 14  CouncilArea      12211 non-null  category
 15  Lattitude        13580 non-null  float64
 16  Longtitude       13580 non-null  float64
 17  Regionname       13580 non-null  category
 18  Propertycount    13580 non-null  int64
 19  MeanRoomsSquare  13580 non-null  float64
 20  AreaRatio        13580 non-null  float64
 21  MonthSale        13580 non-null  category
 22  AgeBuilding      13580 non-null  int64
 23  WeekdaySale      13580 non-null  category
 24  StreetType       13580 non-null  category
 25  Weekend          13580 non-null  category
dtypes: category(10), datetime64[ns](1), float64(8), int64(7)
memory usage: 1.8 MB

None

Index(['Suburb', 'Type', 'Method', 'SellerG', 'CouncilArea', 'Regionname',
       'MonthSale', 'WeekdaySale', 'StreetType', 'Weekend'],
      dtype='object')

In [52]:
# DataFrame.sort_values(by, *, axis=0, ascending=True, inplace=False, kind='quicksort', na_position='last', ignore_index=False, key=None)
# by — имя или список имён столбцов, по значениям которых производится сортировка.
# axis — ось, по которой производится сортировка (0 — строки, 1 — столбцы). По умолчанию сортировка производится по строкам.
# ascending — сортировка по возрастанию (от меньшего к большему). По умолчанию параметр выставлен на True, 
#       для сортировки по убыванию (от большего к меньшему) необходимо выставить его на False.
# ignore_index — создаются ли новые индексы в таблице. По умолчанию выставлен на False и сохраняет индексы изначальной таблицы.
# inplace — производится ли замена исходной таблицы на отсортированную. По умолчанию параметр выставлен на False, 
#       то есть замены не производится. Чтобы переопределить исходную таблицу на отсортированную, необходимо выставить этот параметр на True.

# Отсортируем таблицу по возрастанию цены объектов недвижимости (Price):

melb_df.sort_values(by='Price').head(10)

,Suburb,Rooms,Type,Price,Method,SellerG,Date,Distance,Postcode,Bedroom,...,Longtitude,Regionname,Propertycount,MeanRoomsSquare,AreaRatio,MonthSale,AgeBuilding,WeekdaySale,StreetType,Weekend
2652,Footscray,1,unit,85000.0,PI,Burnham,2016-03-09,6.4,3011,1,...,144.89000,Western Metropolitan,7570,42.000000,1.000000,3,9,2,St,0
1805,other,4,house,131000.0,PI,other,2017-02-25,8.9,3162,4,...,145.02420,Southern Metropolitan,2379,17.222222,-0.525994,2,97,5,St,1
7303,Albion,1,unit,145000.0,PI,Biggin,2016-05-28,13.9,3020,2,...,144.82660,Western Metropolitan,2185,31.500000,0.555556,5,46,5,St,1
1927,Coburg,4,house,145000.0,PI,Jellis,2016-04-06,7.8,3058,3,...,144.96580,Northern Metropolitan,11204,20.500000,-0.531429,4,106,2,Rd,0
7940,Hawthorn,1,unit,160000.0,VB,HAR,2017-08-04,4.6,3122,1,...,145.03730,Southern Metropolitan,11308,42.000000,-0.437500,8,8,4,St,0
12666,Brunswick,1,unit,170000.0,VB,Nelson,2017-09-16,5.2,3056,1,...,144.95188,Northern Metropolitan,11918,42.000000,-0.816860,9,47,5,St,1
8811,Footscray,1,unit,170000.0,PI,Burnham,2017-01-07,5.1,3011,1,...,144.89587,Western Metropolitan,7570,8.666667,-0.071429,1,4,5,St,1
7293,Albion,1,unit,185000.0,S,hockingstuart,2016-08-22,13.9,3020,1,...,144.82720,Western Metropolitan,2185,14.333333,-0.964017,8,41,0,Rd,0
8504,West Footscray,1,unit,185000.0,PI,Jas,2017-04-29,8.2,3012,1,...,144.86720,Western Metropolitan,5058,42.000000,1.000000,4,47,5,St,1
7305,Albion,2,unit,190000.0,SP,Burnham,2016-07-30,13.9,3020,2,...,144.82390,Western Metropolitan,2185,25.200000,1.000000,7,46,5,St,1

In [53]:
# А теперь отсортируем таблицу по убыванию (от самой последней до самой первой) даты продажи объекта (Date). 
# Для этого выставим параметр ascending на False:

melb_df.sort_values(by='Date', ascending=False)

,Suburb,Rooms,Type,Price,Method,SellerG,Date,Distance,Postcode,Bedroom,...,Longtitude,Regionname,Propertycount,MeanRoomsSquare,AreaRatio,MonthSale,AgeBuilding,WeekdaySale,StreetType,Weekend
11144,Northcote,4,house,1955000.0,SP,McGrath,2017-12-08,5.3,3070,4,...,144.99375,Northern Metropolitan,11364,12.600000,0.923664,12,47,4,St,0
11217,Surrey Hills,3,house,1775000.0,PI,Jellis,2017-12-08,10.2,3127,3,...,145.08968,Southern Metropolitan,5457,15.750000,-0.721854,12,47,4,Rd,0
11206,St Kilda,4,house,1600000.0,VB,Gary,2017-12-08,5.0,3182,4,...,144.98324,Southern Metropolitan,13240,16.000000,-0.586028,12,107,4,St,0
11207,Strathmore,7,house,2000000.0,SP,Nelson,2017-12-08,8.2,3041,7,...,144.90587,Western Metropolitan,3284,20.882353,-0.262721,12,18,4,Rd,0
11208,Strathmore,4,house,1610000.0,S,other,2017-12-08,8.2,3041,4,...,144.92243,Western Metropolitan,3284,24.909091,-0.517181,12,62,4,St,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1555,Camberwell,4,house,2650000.0,S,Jellis,2016-03-09,7.8,3124,4,...,145.06860,Southern Metropolitan,8920,18.900000,-0.550535,3,126,2,Rd,0
4510,Oak Park,3,house,892000.0,S,Nelson,2016-03-09,11.5,3046,3,...,144.91740,Northern Metropolitan,2651,18.000000,-0.714609,3,46,2,St,0
4388,Northcote,3,house,1200000.0,S,Nelson,2016-03-09,5.5,3070,3,...,144.99090,Northern Metropolitan,11364,17.857143,-0.264706,3,96,2,St,0
6184,Surrey Hills,3,house,1205000.0,S,Fletchers,2016-01-28,11.2,3127,3,...,145.10060,Southern Metropolitan,5457,18.000000,-0.590909,1,46,3,Rd,0
6183,Surrey Hills,2,unit,813000.0,S,Fletchers,2016-01-28,11.2,3127,2,...,145.10230,Southern Metropolitan,5457,25.200000,0.076923,1,46,3,Rd,0

In [55]:
# отсортируем таблицу сначала по возрастанию расстояния от центра города (Distance), 
# а затем — по возрастанию цены объекта (Price). 
# Для того чтобы вывод был более наглядным, выделим каждую десятую строку из столбцов Distance и Price результирующей таблицы:

melb_df.sort_values(by=['Distance', 'Price']).loc[::10, ['Distance', 'Price']]

       Distance      Price
11428       0.0   387000.0
10512       0.7   600000.0
5727        1.2   485000.0
8671        1.2   595000.0
5736        1.2   740000.0
...         ...        ...
12011      38.0   680000.0
10673      38.0   810000.0
13429      38.0  1155000.0
11102      41.0   650000.0
12728      45.9   650000.0

[1358 rows x 2 columns]

In [57]:
# Предположим, компания McGrath поручила нам восстановить хронологию продаж таунхаусов, 
# у которых площадь участка существенно больше площади здания, чтобы понять, как часто компания справляется с таким сложным видом объектов. 
# Объекты, проданные в один и тот же день, мы бы хотели сортировать по значению коэффициента соотношения площадей. 

# Найдём информацию о таунхаусах (Type), проданных компанией (SellerG) McGrath, 
# у которых коэффициент соотношения площадей здания и участка (AreaRatio) меньше -0.8. Результат отсортируем по дате продажи (Date) 
# в порядке возрастания, а после проведём сортировку по убыванию коэффициента соотношения площадей. 
# Также обновим старые индексы на новые, установив параметр ignore_index на True. 
# Для наглядности результата выберем из таблицы только столбцы Data и AreaRatio:

mask1 = melb_df['AreaRatio'] < -0.8
mask2 = melb_df['Type'] == 'townhouse'
mask3 = melb_df['SellerG'] == 'McGrath'
melb_df[mask1 & mask2 & mask3].sort_values(
    by=['Date', 'AreaRatio'],
    ascending=[True, False],
    ignore_index=True
).loc[:, ['Date', 'AreaRatio']]

        Date  AreaRatio
0 2016-07-26  -0.974922
1 2016-09-24  -0.971831
2 2016-11-27  -0.953608
3 2016-12-11  -0.945946
4 2017-08-04  -0.947368
5 2017-08-04  -0.970874

In [83]:
# Произведите сортировку столбца AreaRatio по убыванию. После сортировки замените индексы таблицы на новые. 
# Какое значение площади здания находится в строке 1558? Ответ округлите до целого числа.
sorted_area = melb_df.copy()
sorted_area.sort_values(by=['AreaRatio'], ascending=False, inplace=True, ignore_index=True)
sorted_area.iloc[1555:1560]['BuildingArea']

1555    116.0
1556    126.0
1557     56.0
1558     77.0
1559     59.0
Name: BuildingArea, dtype: float64

In [78]:
# Сортируем по AreaRatio по убыванию и сбрасываем индексы
df_sorted = melb_df.sort_values(by='AreaRatio', ascending=False).reset_index(drop=True)

# Берем значение площади здания из строки 1558
value = df_sorted.loc[1558, 'BuildingArea']

# Округляем до целого числа
print(round(value))

77

In [74]:
# Найдите таунхаусы (Type) с количеством жилых комнат (Rooms) больше 2. 
# Отсортируйте полученную таблицу сначала по возрастанию числа комнат, 
# а затем по убыванию средней площади комнат (MeanRoomsSquare). 
# Индексы таблицы замените на новые. Какая цена будет у объекта в строке 18? Ответ запишите в виде целого числа.
th = melb_df[(melb_df['Type'] == 'townhouse') & (melb_df['Rooms'] > 2)].copy()
th.sort_values(['Rooms','MeanRoomsSquare'], ascending=[True, False], inplace=True, ignore_index=True)
th.loc[18]

Suburb                     Brighton East
Rooms                                  3
Type                           townhouse
Price                          1300000.0
Method                                PI
SellerG                           Buxton
Date                 2016-09-17 00:00:00
Distance                            10.7
Postcode                            3187
Bedroom                                3
Bathroom                               2
Car                                    2
Landsize                           337.0
BuildingArea                       222.0
CouncilArea                      Bayside
Lattitude                       -37.9196
Longtitude                      145.0205
Regionname         Southern Metropolitan
Propertycount                       6938
MeanRoomsSquare                    27.75
AreaRatio                      -0.205725
MonthSale                              9
AgeBuilding                           16
WeekdaySale                            5
StreetType                            St
Weekend                                1
Name: 18, dtype: object

In [ ]:
# DataFrame.groupby(by=None, axis=<no_default>, level=None, as_index=True, sort=True, group_keys=True, observed=<no_default>, dropna=True)
# by — имя или список имён столбцов, по которым производится группировка.
# axis — ось, по которой производится группировка (0 — строки, 1 — столбцы). По умолчанию группировка производится по строкам.
# as_index — добавляется ли дополнительный индекс к таблице. По умолчанию установлен на True.
# Метод groupby() возвращает объект DataFrameGroupBy, который хранит в себе информацию о том, какие строки относятся к определённой группе, и сам по себе не представляет для нас интереса. 
# Однако к этому объекту можно применять уже знакомые нам агрегирующие методы (mean, median, sum и т. д.), чтобы рассчитывать показатели внутри каждой группы.

# Применим агрегирующую функцию среднего к результату работы groupby(). В качестве столбца для группировки возьмём столбец типа объекта недвижимости (Type):

melb_df.groupby(by='Type').mean(numeric_only=True)

# Если мы хотим видеть тип объекта в качестве отдельного столбца таблицы, мы можем выставить параметр as_index на False:

C:\Users\Yuri\AppData\Local\Temp\ipykernel_27740\938498928.py:10: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  melb_df.groupby(by='Type').mean(numeric_only=True)

,Rooms,Price,Distance,Postcode,Bedroom,Bathroom,Car,Landsize,BuildingArea,Lattitude,Longtitude,Propertycount,MeanRoomsSquare,AreaRatio,AgeBuilding
Type,,,,,,,,,,,,,,,
house,3.260874,1.242665e+06,10.979479,3104.080643,3.229336,1.613822,1.772674,617.181924,152.162553,-37.803795,144.994700,7259.025505,18.996731,-0.490031,55.669700
townhouse,2.837522,9.337351e+05,9.851346,3100.777379,2.814183,1.809695,1.555655,279.606822,134.649710,-37.815782,144.996489,7094.459605,18.569847,-0.094916,26.690305
unit,1.963871,6.051275e+05,7.607391,3110.797481,1.966523,1.183295,1.128936,477.314219,102.235863,-37.823710,144.996363,8199.280080,21.068242,0.319883,39.703016

In [85]:
# Например, давайте сравним средние цены на объекты в зависимости от их типа:

melb_df.groupby('Type')['Price'].mean()

C:\Users\Yuri\AppData\Local\Temp\ipykernel_27740\4244452917.py:3: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  melb_df.groupby('Type')['Price'].mean()

Type
house        1.242665e+06
townhouse    9.337351e+05
unit         6.051275e+05
Name: Price, dtype: float64

In [ ]:
# Теперь давайте выясним, какие регионы (Regionname) наиболее удалены от центра Мельбурна.
# Для этого найдём минимальное значение расстояния от центра города до объекта в зависимости от его региона. Результат отсортируем по убыванию расстояния:

melb_df.groupby('Regionname')['Distance'].min().sort_values(ascending=False)

C:\Users\Yuri\AppData\Local\Temp\ipykernel_27740\2551457561.py:4: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  melb_df.groupby('Regionname')['Distance'].min().sort_values(ascending=False)

Regionname
Western Victoria              29.8
Eastern Victoria              25.2
Northern Victoria             21.8
South-Eastern Metropolitan    14.7
Eastern Metropolitan           7.8
Western Metropolitan           4.3
Southern Metropolitan          0.7
Northern Metropolitan          0.0
Name: Distance, dtype: float64

In [ ]:
# Давайте построим таблицу для анализа продаж по месяцам. Для этого найдём количество продаж, 
# а также среднее и максимальное значения цен объектов недвижимости (Price), сгруппированных по номеру месяца продажи (MonthSale). 
# Результат отсортируем по количеству продаж в порядке убывания:

melb_df.groupby('MonthSale')['Price'].agg(['count', 'mean', 'max']).sort_values(by='count', ascending=False)

C:\Users\Yuri\AppData\Local\Temp\ipykernel_27740\4123448708.py:5: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  melb_df.groupby('MonthSale')['Price'].agg(

           count          mean        max
MonthSale
8           1850  1.056371e+06  6500000.0
7           1835  9.314698e+05  9000000.0
5           1644  1.097807e+06  8000000.0
6           1469  1.068981e+06  7650000.0
3           1408  1.146762e+06  5600000.0
4           1246  1.050479e+06  5500000.0
9           1188  1.126349e+06  6400000.0
10           854  1.135970e+06  6250000.0
11           750  1.142503e+06  5050000.0
12           725  1.144737e+06  5700000.0
2            333  1.169051e+06  4735000.0
1            278  9.397921e+05  5200000.0

In [89]:
# Если вам нужна полная информация обо всех основных статистических характеристиках внутри каждой группы, вы можете воспользоваться методом agg(), 
# передав в качестве его параметра строку 'describe':

melb_df.groupby('MonthSale')['Price'].agg('describe')

C:\Users\Yuri\AppData\Local\Temp\ipykernel_27740\2271230498.py:4: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  melb_df.groupby('MonthSale')['Price'].agg('describe')

,count,mean,std,min,25%,50%,75%,max
MonthSale,,,,,,,,
1,278.0,9.397921e+05,577668.924214,170000.0,570500.0,795000.0,1111250.0,5200000.0
2,333.0,1.169051e+06,671564.357417,131000.0,710000.0,1020000.0,1478000.0,4735000.0
3,1408.0,1.146762e+06,709573.596867,85000.0,680000.0,945000.0,1400000.0,5600000.0
4,1246.0,1.050479e+06,591892.902979,145000.0,655000.0,905500.0,1298750.0,5500000.0
5,1644.0,1.097807e+06,668492.867996,145000.0,650000.0,905000.0,1371250.0,8000000.0
6,1469.0,1.068981e+06,606010.069052,222000.0,660000.0,900000.0,1325000.0,7650000.0
7,1835.0,9.314698e+05,537390.803161,190000.0,586750.0,800000.0,1150000.0,9000000.0
8,1850.0,1.056371e+06,619617.476541,160000.0,635000.0,892000.0,1310000.0,6500000.0
9,1188.0,1.126349e+06,608734.690742,170000.0,725000.0,980000.0,1360000.0,6400000.0
10,854.0,1.135970e+06,692950.251627,250000.0,652625.0,950000.0,1416500.0,6250000.0
11,750.0,1.142503e+06,703666.227892,240000.0,671750.0,950000.0,1399125.0,5050000.0
12,725.0,1.144737e+06,706549.007161,250000.0,667500.0,938000.0,1412000.0,5700000.0

In [ ]:
# После базовых математических функций наиболее частым агрегированием является подсчёт числа уникальных значений. 
# Так, например, мы можем вычислить число уникальных риелторских компаний в зависимости от региона, чтобы понять, 
# в каких регионах конкуренция на рынке недвижимости меньше. Это можно сделать, передав в параметр метода agg() строку 'nunique'. 

# Более того, метод agg() поддерживает использование и других функций. Передадим дополнительно встроенную функцию set, 
# чтобы получить множество из агентств недвижимости, которые работают в каждом из регионов:

melb_df.groupby('Regionname')['SellerG'].agg(['nunique', set])

C:\Users\Yuri\AppData\Local\Temp\ipykernel_27740\2514222188.py:8: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  melb_df.groupby('Regionname')['SellerG'].agg(

,nunique,set
Regionname,,
Eastern Metropolitan,26,"{Ray, McGrath, RW, HAR, Nelson, Buxton, other,..."
Eastern Victoria,11,"{Harcourts, Ray, Eview, other, McGrath, O'Brie..."
Northern Metropolitan,40,"{Ray, Cayzer, Alexkarbon, Eview, Nick, Hodges,..."
Northern Victoria,11,"{Ray, Raine, other, McDonald, LITTLE, McGrath,..."
South-Eastern Metropolitan,25,"{Ray, Eview, Hodges, McGrath, RW, HAR, Nelson,..."
Southern Metropolitan,38,"{Ray, Cayzer, Eview, Nick, Hodges, McGrath, RW..."
Western Metropolitan,34,"{Ray, Alexkarbon, Hodges, McGrath, RW, HAR, Do..."
Western Victoria,6,"{Ray, Raine, other, HAR, hockingstuart, YPA}"

In [93]:
# Сгруппируйте данные по признаку количества комнат и найдите среднюю цену объектов недвижимости в каждой группе. 
# В качестве ответа запишите количество комнат, для которых средняя цена наибольшая.
melb_df.groupby('Rooms')['Price'].agg('mean')

Rooms
1     4.338245e+05
2     7.750812e+05
3     1.076081e+06
4     1.445282e+06
5     1.870260e+06
6     1.849366e+06
7     1.920700e+06
8     1.602750e+06
10    9.000000e+05
Name: Price, dtype: float64

In [94]:
# Какой регион имеет наименьшее стандартное отклонение по географической широте (Lattitude)?
# В качестве ответа запишите название этого региона.
melb_df.groupby('Regionname')['Lattitude'].agg('std')

C:\Users\Yuri\AppData\Local\Temp\ipykernel_27740\1235696781.py:3: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  melb_df.groupby('Regionname')['Lattitude'].agg('std')

Regionname
Eastern Metropolitan          0.047890
Eastern Victoria              0.147067
Northern Metropolitan         0.049639
Northern Victoria             0.084455
South-Eastern Metropolitan    0.073411
Southern Metropolitan         0.043080
Western Metropolitan          0.051251
Western Victoria              0.011579
Name: Lattitude, dtype: float64

In [102]:
# Какая риелторская компания (SellerG) имеет наименьшую общую выручку за период с 1 мая по 1 сентября (включительно) 2017 года?
# Для ответа на этот вопрос рассчитайте сумму продаж (Price) каждой компании в заданный период.
# Не забудьте перевести даты в формат datetime.
melb_df[(melb_df['Date'] >= pd.to_datetime('2017-05-01')) & (melb_df['Date'] <= pd.to_datetime('2017-09-01'))].groupby('SellerG')['Price'].agg(['sum']).sort_values(by='sum', ascending=True)

C:\Users\Yuri\AppData\Local\Temp\ipykernel_27740\1258013610.py:4: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  melb_df[(melb_df['Date'] >= pd.to_datetime('2017-05-01')) & (melb_df['Date'] <= pd.to_datetime('2017-09-01'))].groupby('SellerG')['Price'].agg(['sum']).sort_values(by='sum', ascending=True)

                       sum
SellerG
LITTLE           2742000.0
Cayzer           4439000.0
Burnham          4550500.0
Moonee           7328000.0
Thomson          8332000.0
Bells            8656000.0
Alexkarbon      10985000.0
McDonald        14637500.0
Rendina         15422276.0
Nick            16890000.0
Douglas         18341000.0
Buckingham      19033000.0
C21             19515000.0
Eview           19791500.0
Collins         20217000.0
Philip          22051800.0
Chisholm        23225000.0
Williams        23297000.0
Love            23365500.0
Purplebricks    23401000.0
O'Brien         23855508.0
HAR             25568000.0
Village         26473000.0
RW              29261000.0
Raine           30687700.0
Stockdale       35409800.0
Sweeney         36882750.0
Gary            39138400.0
Hodges          43231000.0
YPA             46354350.0
Miles           47582000.0
Kay             48569500.0
RT              50498000.0
Brad            55955000.0
Jas             59281600.0
Harcourts       68720250.0
McGrath         78386500.0
Greg            85621000.0
Woodards        85977500.0
Noel            88129800.0
Fletchers      108847700.0
Biggin         110429500.0
Buxton         219104000.0
Ray            249572986.0
Marshall       253957888.0
hockingstuart  282834310.0
Barry          296723050.0
other          365038432.0
Nelson         379767500.0
Jellis         414121833.0

In [103]:
# мы уже умеем строить таблицу, которая показывает зависимость медианной цены и площади здания от числа комнат:

melb_df.groupby('Rooms')[['Price', 'BuildingArea']].median()

           Price  BuildingArea
Rooms
1       385000.0         107.0
2       690000.0         126.0
3       950000.0         126.0
4      1285000.0         142.0
5      1660000.0         176.0
6      1800000.0         126.0
7      1496000.0         216.5
8      1515000.0         126.0
10      900000.0         126.0

In [104]:
# Также можно построить таблицу, в которой мы будем учитывать не только число комнат, но и тип здания (Type). 
# Для этого в параметрах метода groupby() укажем список из нескольких интересующих нас столбцов.

melb_df.groupby(['Rooms', 'Type'])['Price'].mean()

C:\Users\Yuri\AppData\Local\Temp\ipykernel_27740\3264542530.py:4: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  melb_df.groupby(['Rooms', 'Type'])['Price'].mean()

Rooms  Type
1      house        8.668655e+05
       townhouse    5.927045e+05
       unit         3.899289e+05
2      house        1.017238e+06
       townhouse    7.101585e+05
       unit         6.104905e+05
3      house        1.109233e+06
       townhouse    9.847087e+05
       unit         8.505963e+05
4      house        1.462283e+06
       townhouse    1.217092e+06
       unit         1.037476e+06
5      house        1.877327e+06
       townhouse    1.035000e+06
       unit                  NaN
6      house        1.869508e+06
       townhouse             NaN
       unit         5.200000e+05
7      house        1.920700e+06
       townhouse             NaN
       unit                  NaN
8      house        1.510286e+06
       townhouse             NaN
       unit         2.250000e+06
10     house        9.000000e+05
       townhouse             NaN
       unit                  NaN
Name: Price, dtype: float64

In [105]:
# Для того, чтобы финальный результат был представлен в виде сводной таблицы 
# (первый группировочный признак по строкам, а второй — по столбцам), а не в виде Series с иерархическими индексами, 
# к результату чаще всего применяют метод unstack(), который позволяет переопределить вложенный индекс в виде столбцов таблицы:

melb_df.groupby(['Rooms', 'Type'])['Price'].mean().unstack()

C:\Users\Yuri\AppData\Local\Temp\ipykernel_27740\3432864227.py:5: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  melb_df.groupby(['Rooms', 'Type'])['Price'].mean().unstack()

Type          house     townhouse          unit
Rooms
1      8.668655e+05  5.927045e+05  3.899289e+05
2      1.017238e+06  7.101585e+05  6.104905e+05
3      1.109233e+06  9.847087e+05  8.505963e+05
4      1.462283e+06  1.217092e+06  1.037476e+06
5      1.877327e+06  1.035000e+06           NaN
6      1.869508e+06           NaN  5.200000e+05
7      1.920700e+06           NaN           NaN
8      1.510286e+06           NaN  2.250000e+06
10     9.000000e+05           NaN           NaN

In [ ]:
# DataFrame.pivot_table(values=None, index=None, columns=None, aggfunc='mean', fill_value=None, margins=False, dropna=True, margins_name='All', observed=<no_default>, sort=True)
# values — имя столбца, по которому необходимо получить сводные данные, применяя агрегирующую функцию;
# index — имя столбца, значения которого станут строками сводной таблицы;
# columns — имя столбца, значения которого станут столбцами сводной таблицы;
# aggfunc — имя или список имён агрегирующих функций (по умолчанию — подсчёт среднего, 'mean');
# fill_value — значение, которым необходимо заполнить пропуски (по умолчанию пропуски не заполняются).

# Давайте построим ту же самую таблицу, но уже с использованием метода pivot_table. В качестве параметра values укажем столбец Price, 
# в качестве индексов сводной таблицы возьмём Rooms, а в качестве столбцов — Type. Агрегирующую функцию оставим по умолчанию (среднее). 
# Дополнительно заменим пропуски в таблице на значение 0. Финальный результат для наглядности вывода округлим с помощью метода round() до целых.

melb_df.pivot_table(
    values='Price',
    index='Rooms',
    columns='Type',
    fill_value=0
).round()

C:\Users\Yuri\AppData\Local\Temp\ipykernel_27740\2212522254.py:12: FutureWarning: The default value of observed=False is deprecated and will change to observed=True in a future version of pandas. Specify observed=False to silence this warning and retain the current behavior
  melb_df.pivot_table(

Type       house  townhouse       unit
Rooms
1       866866.0   592705.0   389929.0
2      1017238.0   710158.0   610491.0
3      1109233.0   984709.0   850596.0
4      1462283.0  1217092.0  1037476.0
5      1877327.0  1035000.0        0.0
6      1869508.0        0.0   520000.0
7      1920700.0        0.0        0.0
8      1510286.0        0.0  2250000.0
10      900000.0        0.0        0.0

In [ ]:
# А теперь давайте проанализируем продажи в каждом из регионов в зависимости от того, будний был день или выходной. 
# Для этого построим сводную таблицу, в которой строками будут являться названия регионов (Regionname), 
# а в столбцах будет располагаться наш «признак-мигалка» выходного дня (Weekend), который равен 1, если день был выходным, и 0 — в противном случае. 
# В качестве значений сводной таблицы возьмём количество продаж.

melb_df.pivot_table(
    values='Price',
    index='Regionname',
    columns='Weekend',
    aggfunc='count'
)

C:\Users\Yuri\AppData\Local\Temp\ipykernel_27740\301346009.py:3: FutureWarning: The default value of observed=False is deprecated and will change to observed=True in a future version of pandas. Specify observed=False to silence this warning and retain the current behavior
  melb_df.pivot_table(

Weekend                        0     1
Regionname
Eastern Metropolitan         447  1024
Eastern Victoria              13    40
Northern Metropolitan       1258  2632
Northern Victoria             11    30
South-Eastern Metropolitan   123   327
Southern Metropolitan       1534  3161
Western Metropolitan         960  1988
Western Victoria               8    24

In [108]:
# Разберём ещё один пример: найдём, как зависит средняя и медианная площадь участка (Landsize) от типа объекта (Type) и его региона (Regionname). 
# Чтобы посмотреть несколько статистических параметров, нужно передать в аргумент aggfunc список из агрегирующих функций. 
# Построим такую сводную таблицу, где пропущенные значения заменим на 0:

melb_df.pivot_table(
    values='Landsize',
    index='Regionname',
    columns='Type',
    aggfunc=['median', 'mean'],
    fill_value=0
)

C:\Users\Yuri\AppData\Local\Temp\ipykernel_27740\2784524651.py:5: FutureWarning: The default value of observed=False is deprecated and will change to observed=True in a future version of pandas. Specify observed=False to silence this warning and retain the current behavior
  melb_df.pivot_table(
C:\Users\Yuri\AppData\Local\Temp\ipykernel_27740\2784524651.py:5: FutureWarning: The default value of observed=False is deprecated and will change to observed=True in a future version of pandas. Specify observed=False to silence this warning and retain the current behavior
  melb_df.pivot_table(

                           median                          mean              \
Type                        house townhouse   unit        house   townhouse
Regionname
Eastern Metropolitan        674.0     233.5  203.0   717.422847  269.440678
Eastern Victoria            843.0       0.0  230.0  3108.960000    0.000000
Northern Metropolitan       459.5     134.0    0.0   619.249092  317.325733
Northern Victoria           724.0       0.0    0.0  3355.463415    0.000000
South-Eastern Metropolitan  630.5     240.0  199.0   664.306701  212.160000
Southern Metropolitan       586.0     246.0    0.0   569.643881  278.858824
Western Metropolitan        531.0     198.0   62.0   507.883406  244.560669
Western Victoria            599.5       0.0    0.0   655.500000    0.000000


Type                              unit
Regionname
Eastern Metropolitan        330.444444
Eastern Victoria            295.333333
Northern Metropolitan       495.026538
Northern Victoria             0.000000
South-Eastern Metropolitan  357.864865
Southern Metropolitan       466.380245
Western Metropolitan        557.637232
Western Victoria              0.000000

In [109]:
# Многомерные 
# Давайте построим таблицу, в которой по индексам будут располагаться признаки метода продажи (Method) и типа объекта (Type), 
# по столбцам — наименование региона (Regionname), а на пересечении строк и столбцов будет стоять медианная цена объекта (Price):

melb_df.pivot_table(
    values='Price',
    index=['Method','Type'],
    columns='Regionname',
    aggfunc='median',
    fill_value=0
)

C:\Users\Yuri\AppData\Local\Temp\ipykernel_27740\1870103000.py:5: FutureWarning: The default value of observed=False is deprecated and will change to observed=True in a future version of pandas. Specify observed=False to silence this warning and retain the current behavior
  melb_df.pivot_table(

Regionname        Eastern Metropolitan  Eastern Victoria  \
Method Type
PI     house                 1244000.0          780000.0
       townhouse              760000.0               0.0
       unit                   650000.0               0.0
S      house                 1127000.0          675000.0
       townhouse              828000.0               0.0
       unit                   645750.0          492000.0
SA     house                  932500.0          950000.0
       townhouse              807500.0               0.0
       unit                        0.0               0.0
SP     house                 1050000.0          672500.0
       townhouse              910000.0               0.0
       unit                   515000.0          400000.0
VB     house                 1100000.0          712500.0
       townhouse              892500.0               0.0
       unit                   500000.0               0.0

Regionname        Northern Metropolitan  Northern Victoria  \
Method Type
PI     house                   900000.0           500000.0
       townhouse               632500.0                0.0
       unit                    410000.0                0.0
S      house                   920000.0           555000.0
       townhouse               750000.0                0.0
       unit                    525500.0                0.0
SA     house                   817500.0           540000.0
       townhouse               425000.0                0.0
       unit                    616000.0                0.0
SP     house                   900000.0           521000.0
       townhouse               690000.0                0.0
       unit                    470000.0                0.0
VB     house                  1050000.0           690000.0
       townhouse               640000.0                0.0
       unit                    450000.0                0.0

Regionname        South-Eastern Metropolitan  Southern Metropolitan  \
Method Type
PI     house                        865000.0              1725000.0
       townhouse                   1190000.0              1055000.0
       unit                         525000.0               571250.0
S      house                        883300.0              1611000.0
       townhouse                    875000.0              1135000.0
       unit                         606000.0               655000.0
SA     house                        880000.0              1390000.0
       townhouse                         0.0              1141000.0
       unit                              0.0               580000.0
SP     house                        770000.0              1521750.0
       townhouse                    800000.0              1162500.0
       unit                         601000.0               550000.0
VB     house                        850000.0              1800000.0
       townhouse                         0.0              1250000.0
       unit                         700000.0               500000.0

Regionname        Western Metropolitan  Western Victoria
Method Type
PI     house                  870000.0          630000.0
       townhouse              670000.0               0.0
       unit                   360000.0               0.0
S      house                  870000.0          397500.0
       townhouse              729000.0               0.0
       unit                   489000.0               0.0
SA     house                  772500.0               0.0
       townhouse              467500.0               0.0
       unit                   571000.0               0.0
SP     house                  865000.0          360000.0
       townhouse              702500.0               0.0
       unit                   460000.0               0.0
VB     house                  880000.0               0.0
       townhouse              689500.0               0.0
       unit                   420000.0               0.0

In [110]:
# Запишем сводную таблицу, которую мы создавали ранее в переменную pivot:

pivot = melb_df.pivot_table(
    values='Landsize',
    index='Regionname',
    columns='Type',
    aggfunc=['median', 'mean'],
    fill_value=0
)
# Выведем её столбцы с помощью атрибута columns:

pivot.columns

C:\Users\Yuri\AppData\Local\Temp\ipykernel_27740\3942122110.py:3: FutureWarning: The default value of observed=False is deprecated and will change to observed=True in a future version of pandas. Specify observed=False to silence this warning and retain the current behavior
  pivot = melb_df.pivot_table(
C:\Users\Yuri\AppData\Local\Temp\ipykernel_27740\3942122110.py:3: FutureWarning: The default value of observed=False is deprecated and will change to observed=True in a future version of pandas. Specify observed=False to silence this warning and retain the current behavior
  pivot = melb_df.pivot_table(

MultiIndex([('median',     'house'),
            ('median', 'townhouse'),
            ('median',      'unit'),
            (  'mean',     'house'),
            (  'mean', 'townhouse'),
            (  'mean',      'unit')],
           names=[None, 'Type'])

In [111]:
# Так, из таблицы pivot мы можем получить средние значения площадей участков для типа здания unit, просто последовательно обратившись по имени столбцов:

display(pivot['mean']['unit'])

Regionname
Eastern Metropolitan          330.444444
Eastern Victoria              295.333333
Northern Metropolitan         495.026538
Northern Victoria               0.000000
South-Eastern Metropolitan    357.864865
Southern Metropolitan         466.380245
Western Metropolitan          557.637232
Western Victoria                0.000000
Name: unit, dtype: float64

In [112]:
# Аналогично производится и фильтрация данных. Например, если нам нужны регионы, 
# в которых средняя площадь здания для домов типа house меньше их медианной площади, то мы можем найти их следующим образом:

mask = pivot['mean']['house'] < pivot['median']['house']
filtered_pivot = pivot[mask]
display(filtered_pivot)

                      median                        mean              \
Type                   house townhouse  unit       house   townhouse
Regionname
Southern Metropolitan  586.0     246.0   0.0  569.643881  278.858824
Western Metropolitan   531.0     198.0  62.0  507.883406  244.560669


Type                         unit
Regionname
Southern Metropolitan  466.380245
Western Metropolitan   557.637232

In [113]:
# Чтобы получить индексы отфильтрованной таблицы, можно воспользоваться атрибутом index и обернуть результат в список:

print(list(filtered_pivot.index))
# ['Southern Metropolitan', 'Western Metropolitan']

['Southern Metropolitan', 'Western Metropolitan']

In [116]:
# На самом деле мультииндексные таблицы можно создавать и вручную. Давайте посмотрим на синтаксис данной конструкции:

import numpy as np
mser = pd.Series(
    np.random.rand(8),
	index=[['white','white','white','blue','blue','red','red','red'], 
           ['up','down','right','up','down','up','down','left']])
display(mser)
print(mser.index)

white  up       0.654300
       down     0.996790
       right    0.652769
blue   up       0.081241
       down     0.376733
red    up       0.491006
       down     0.092978
       left     0.105112
dtype: float64

MultiIndex([('white',    'up'),
            ('white',  'down'),
            ('white', 'right'),
            ( 'blue',    'up'),
            ( 'blue',  'down'),
            (  'red',    'up'),
            (  'red',  'down'),
            (  'red',  'left')],
           )

In [117]:
# Аналогично создаются DataFrame со вложенными признаками (вложенными столбцами) — для этого вложенный список передаётся в параметр columns при инициализации таблицы:

mframe = pd.DataFrame(
    np.random.randn(16).reshape(4,4),
    index=[['white','white','red','red'], ['up','down','up','down']],
    columns=[['pen','pen','paper','paper'],[1,2,1,2]]
)
display(mframe)

                 pen               paper
                   1         2         1         2
white up    0.787276 -0.961085  0.137615 -1.036531
      down -0.403273 -0.948063  1.871533 -2.090702
red   up   -0.742111 -0.948454 -0.430013  1.587558
      down  0.404963 -0.505874 -0.839772  0.676098

In [118]:
# Составьте сводную таблицу, которая показывает зависимость медианной площади (BuildingArea) здания 
# от типа объекта недвижимости (Type) и количества жилых комнат в доме (Rooms). Для какой комбинации признаков площадь здания наибольшая?
# В качестве ответа запишите эту комбинацию (тип здания, число комнат) через запятую, без пробелов.

pivot = melb_df.pivot_table(
    values='BuildingArea',
    index='Type',
    columns='Rooms',
    aggfunc=['median'],
    fill_value=0)

display(pivot)

C:\Users\Yuri\AppData\Local\Temp\ipykernel_27740\2088184221.py:5: FutureWarning: The default value of observed=False is deprecated and will change to observed=True in a future version of pandas. Specify observed=False to silence this warning and retain the current behavior
  pivot = melb_df.pivot_table(

          median
Rooms         1      2      3      4      5      6      7      8      10
Type
house      126.0  126.0  126.0  141.0  177.0  126.0  216.5  126.0  126.0
townhouse   88.0  114.0  126.0  159.5  152.0    0.0    0.0    0.0    0.0
unit        69.5  110.0  126.0  126.0    0.0  171.0    0.0  126.0    0.0

In [ ]:
# Составьте сводную таблицу, которая показывает зависимость медианной цены объекта недвижимости (Price) от риелторского агентства (SellerG) и типа здания (Type).
# Во вновь созданной таблице найдите агентство, у которого медианная цена для зданий типа unit максимальна. В качестве ответа запишите название этого агентства.
pivot = melb_df.pivot_table(
    values='Price',
    index='Type',
    columns='SellerG',
    aggfunc=['median'],
    fill_value=0)

display(pivot)

# Находим позицию максимального значения
max_value = pivot.loc['unit'].idxmax() # для поиска строки аналогично, только нужно название колонки 
print(max_value)

C:\Users\Yuri\AppData\Local\Temp\ipykernel_27740\846548859.py:3: FutureWarning: The default value of observed=False is deprecated and will change to observed=True in a future version of pandas. Specify observed=False to silence this warning and retain the current behavior
  pivot = melb_df.pivot_table(

              median                                                      \
SellerG   Alexkarbon     Barry     Bells     Biggin      Brad Buckingham
Type
house      1036250.0  830000.0  692500.0  1151750.0  875000.0   830000.0
townhouse   935000.0  727500.0  430500.0   675000.0  700000.0   820000.0
unit        560000.0  502000.0  457500.0   548000.0  465000.0   553000.0

                                                     ...                       \
SellerG     Burnham     Buxton       C21     Cayzer  ...    Rendina Stockdale
Type                                                 ...
house      922500.0  1323750.0  836500.0  1505000.0  ...  1190000.0  715500.0
townhouse       0.0  1030000.0  768750.0  1450000.0  ...   750000.0  550000.0
unit       305000.0   670000.0  625500.0   707500.0  ...   459000.0  410000.0

                                                                          \
SellerG     Sweeney    Thomson   Village   Williams   Woodards       YPA
Type
house      850000.0  1177000.0  973500.0  1161000.0  1261000.0  596250.0
townhouse  728000.0   500000.0  727500.0   735000.0   865500.0  498500.0
unit       381000.0   495000.0  420000.0   577000.0   600000.0  443500.0


SellerG   hockingstuart     other
Type
house         1055000.0  901000.0
townhouse      935000.0  840500.0
unit           566000.0  535000.0

[3 rows x 50 columns]

('median', 'Nick')

In [5]:
import pandas as pd

movies_orig = pd.read_csv('data/movies.csv')
movies = movies_orig.copy()
print(movies['title'].nunique())
movies.head()

9737

,movieId,title,genres
0,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy
1,2,Jumanji (1995),Adventure|Children|Fantasy
2,3,Grumpier Old Men (1995),Comedy|Romance
3,4,Waiting to Exhale (1995),Comedy|Drama|Romance
4,5,Father of the Bride Part II (1995),Comedy

In [ ]:
ratings1_orig = pd.read_csv('data/ratings1.csv')
ratings1 = ratings1_orig.copy()
display(ratings1['userId'].nunique())
ratings1.head()

274

   userId  movieId  rating
0       1        1     4.0
1       1        3     4.0
2       1        6     4.0
3       1       47     5.0
4       1       50     5.0

In [26]:
dates_orig = pd.read_csv('data/dates.csv')
dates = dates_orig.copy()
display(pd.to_datetime(dates['date']).dt.year.value_counts())
dates.info()

date
2000    10061
2017     8198
2007     7114
2016     6703
2015     6616
2018     6418
1996     6040
2005     5813
2012     4656
2008     4351
2009     4158
2006     4059
2003     4014
2001     3922
2002     3478
2004     3279
1999     2439
2010     2301
1997     1916
2011     1690
2013     1664
2014     1439
1998      507
Name: count, dtype: int64

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100836 entries, 0 to 100835
Data columns (total 1 columns):
 #   Column  Non-Null Count   Dtype
---  ------  --------------   -----
 0   date    100836 non-null  object
dtypes: object(1)
memory usage: 787.9+ KB

In [29]:
# pandas.concat(objs, *, axis=0, join='outer', ignore_index=False, keys=None, levels=None, names=None, verify_integrity=False, sort=False, copy=None)
# objs — список объектов DataFrame ([df1, df2,…]), которые должны быть сконкатенированы;
# axis — ось определяет направление конкатенации: 0 — конкатенация по строкам (по умолчанию), 1 — конкатенация по столбцам;
# join — либо inner (пересечение), либо outer (объединение); рассмотрим этот момент немного позже;
# ignore_index — по умолчанию установлено значение False, которое позволяет значениям индекса оставаться такими, какими они были в исходных данных. 
#       Если установлено значение True, параметр будет игнорировать исходные значения и повторно назначать значения индекса в последовательном порядке.

ratings2_orig = pd.read_csv('data/ratings2.csv')
ratings2 = ratings2_orig.copy()

ratings = pd.concat([ratings1, ratings2], ignore_index=True)
display(ratings)

        userId  movieId  rating
0            1        1     4.0
1            1        3     4.0
2            1        6     4.0
3            1       47     5.0
4            1       50     5.0
...        ...      ...     ...
100832     610   166534     4.0
100833     610   168248     5.0
100834     610   168250     5.0
100835     610   168252     5.0
100836     610   170875     3.0

[100837 rows x 3 columns]

In [30]:
# Казалось бы, совсем другое дело! Но это ещё не всё. Давайте узнаем количество строк в таблицах ratings и dates, ведь нам предстоит вертикально склеить их между собой:

print('Число строк в таблице ratings: ', ratings.shape[0])
print('Число строк в таблице dates: ', dates.shape[0])
print(ratings.shape[0] == dates.shape[0])

Число строк в таблице ratings:  100837
Число строк в таблице dates:  100836
False

In [31]:
# На самом деле очень просто: при выгрузке данных информация об оценках какого-то  пользователя попала в обе таблицы (ratings1 и ratings2). 
# В результате конкатенации случилось дублирование строк. В данном примере их легко найти — выведем последнюю строку таблицы ratings1 и первую строку таблицы ratings2:

display(ratings1.tail(1))
display(ratings2.head(1))

       userId  movieId  rating
40000     274     5621     2.0

   userId  movieId  rating
0     274     5621     2.0

In [32]:
# Чтобы очистить таблицу от дублей, мы можем воспользоваться методом DataFrame drop_duplicates(), 
# который удаляет повторяющиеся строки в таблице. Не забываем обновить индексы после удаления дублей, 
# выставив параметр ignore_index в методе drop_duplicates() на значение True:

ratings = ratings.drop_duplicates(ignore_index=True)
print('Число строк в таблице ratings: ', ratings.shape[0])

Число строк в таблице ratings:  100836

In [33]:
# Наконец, мы можем добавить к нашей таблице с оценками даты их выставления. Для этого конкатенируем таблицы ratings и dates по столбцам:

ratings_dates = pd.concat([ratings, dates], axis=1)
display(ratings_dates.tail(7))

        userId  movieId  rating                 date
100829     610   164179     5.0  2017-05-03 21:07:11
100830     610   166528     4.0  2017-05-04 06:29:25
100831     610   166534     4.0  2017-05-03 21:53:22
100832     610   168248     5.0  2017-05-03 22:21:31
100833     610   168250     5.0  2017-05-08 19:50:47
100834     610   168252     5.0  2017-05-03 21:19:12
100835     610   170875     3.0  2017-05-03 21:20:15

In [ ]:
# Задание 6.3

# В ваше распоряжение предоставлена директория users ('./Root/users'). В данной директории содержатся csv-файлы, в каждом из которых хранится информация об идентификаторах пользователей (user_id) и ссылках на их фотографии (image_url). Количество файлов в директории может быть любым.
# Вам необходимо написать функцию concat_user_files(path), параметром которой является path — путь до директории.
# Функция должна:
# Объединить информацию из всех csv-файлов в единый DataFrame.
# Удалить дубликаты.
# Обновить индексы результирующей таблицы.
# Отсортировать пользователей по числовой части user_id (игнорируя буквенную часть).

import pandas as pd
import os

def concat_user_files(path):
    files = os.listdir(path)
     # 1. Список всех CSV-файлов в директории
    files = [f for f in os.listdir(path)]

    # 2. Чтение всех файлов в список DataFrame
    dfs = [pd.read_csv(os.path.join(path, file)) for file in files]

    # 3. Объединение всех DataFrame в один
    df = pd.concat(dfs, ignore_index=True)

    # 4. Удаление дубликатов
    df = df.drop_duplicates()
    
    # 5. Сброс индексов
    df = df.reset_index(drop=True) 

    # 5. Сортировка по числовой части user_id
    df['user_num'] = df['user_id'].str.extract(r'(\d+)').astype(int)
    df = df.sort_values('user_num').drop(columns='user_num')

    # 6. Сброс индексов
    df = df.reset_index(drop=True) 
    
    return df

# print(concat_user_files('./Root/users'))

In [ ]:
# DataFrame.join(other, on=None, how='left', lsuffix='', rsuffix='', sort=False, validate=None)[source]
# other — таблица, которую мы присоединяем. При объединении она является «правой», а исходная таблица, от имени которой вызывается метод, является «левой».
# how — параметр типа объединения. Он может принимать значения 'inner', 'left' (left outer), 'right' (right outer), и 'outer' (full outer). По умолчанию параметр установлен на 'left'.
# on — параметр, который определяет, по какому столбцу в «левой» таблице происходит объединение по индексам из «правой».
# lsuffix и rsuffix — дополнения (суффиксы) к названиям одноимённых столбцов в «левой» и «правой» таблицах.

In [34]:
# Проверим это, объединив таблицы типом left. Так как в наших таблицах есть одноимённые столбцы, установим один из суффиксов, чтобы избежать ошибки:

joined_false = ratings_dates.join(
    movies,
    rsuffix='_right',
    how='left'
)
display(joined_false)

,userId,movieId,rating,date,movieId_right,title,genres
0,1,1,4.0,2000-07-30 18:45:03,1.0,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy
1,1,3,4.0,2000-07-30 18:20:47,2.0,Jumanji (1995),Adventure|Children|Fantasy
2,1,6,4.0,2000-07-30 18:37:04,3.0,Grumpier Old Men (1995),Comedy|Romance
3,1,47,5.0,2000-07-30 19:03:35,4.0,Waiting to Exhale (1995),Comedy|Drama|Romance
4,1,50,5.0,2000-07-30 18:48:51,5.0,Father of the Bride Part II (1995),Comedy
...,...,...,...,...,...,...,...
100831,610,166534,4.0,2017-05-03 21:53:22,NaN,NaN,NaN
100832,610,168248,5.0,2017-05-03 22:21:31,NaN,NaN,NaN
100833,610,168250,5.0,2017-05-08 19:50:47,NaN,NaN,NaN
100834,610,168252,5.0,2017-05-03 21:19:12,NaN,NaN,NaN
100835,610,170875,3.0,2017-05-03 21:20:15,NaN,NaN,NaN

In [35]:
# Однако это не тот результат, который мы хотели, ведь мы не получили соответствия фильмов и их рейтингов. 
# Чтобы совместить таблицы по ключевому столбцу с помощью метода join(), необходимо использовать ключевой столбец в «правой» таблице в качестве индекса. 
# Это можно сделать с помощью метода set_index(). Также необходимо указать название ключа в параметре on.

joined = ratings_dates.join(
    movies.set_index('movieId'),
    on='movieId',
    how='left'
)
display(joined.head())

,userId,movieId,rating,date,title,genres
0,1,1,4.0,2000-07-30 18:45:03,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy
1,1,3,4.0,2000-07-30 18:20:47,Grumpier Old Men (1995),Comedy|Romance
2,1,6,4.0,2000-07-30 18:37:04,Heat (1995),Action|Crime|Thriller
3,1,47,5.0,2000-07-30 19:03:35,Seven (a.k.a. Se7en) (1995),Mystery|Thriller
4,1,50,5.0,2000-07-30 18:48:51,"Usual Suspects, The (1995)",Crime|Mystery|Thriller

In [ ]:
# DataFrame.merge(right, how='inner', on=None, left_on=None, right_on=None, left_index=False, right_index=False, sort=False, suffixes=('_x', '_y'), 
#                 copy=None, indicator=False, validate=None)[source]
# right — присоединяемая таблица. По умолчанию она является «правой».
# how — параметр типа объединения. По умолчанию принимает значение 'inner'.
# on — параметр, который определяет, по какому столбцу происходит объединение. Определяется автоматически, но рекомендуется указывать вручную.
# left_on — если названия столбцов в «левой» и «правой» таблицах не совпадают, то данный параметр отвечает за наименования ключевого столбца исходной таблицы.
# right_on — аналогично предыдущему, параметр отвечает за наименование ключевого столбца присоединяемой таблицы.

In [36]:
# Посмотрим на метод merge() в действии. Произведём слияние наших таблиц и получим ту же таблицу, что и ранее:

merged = ratings_dates.merge(
    movies,
    on='movieId',
    how='left'
)
display(merged.head())

,userId,movieId,rating,date,title,genres
0,1,1,4.0,2000-07-30 18:45:03,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy
1,1,3,4.0,2000-07-30 18:20:47,Grumpier Old Men (1995),Comedy|Romance
2,1,6,4.0,2000-07-30 18:37:04,Heat (1995),Action|Crime|Thriller
3,1,47,5.0,2000-07-30 19:03:35,Seven (a.k.a. Se7en) (1995),Mystery|Thriller
4,1,50,5.0,2000-07-30 18:48:51,"Usual Suspects, The (1995)",Crime|Mystery|Thriller

In [37]:
# Проверим, что число строк в таблице ratings_dates совпадает с числом строк в результирующей таблице merged:

print('Число строк в таблице ratings_dates: ', ratings_dates.shape[0])
print('Число строк в таблице merged: ', merged.shape[0])
print(ratings_dates.shape[0] == merged.shape[0])

Число строк в таблице ratings_dates:  100836
Число строк в таблице merged:  100836
True

In [38]:
# Возникает вопрос: почему мы выбрали тип объединения left, а не full, например?
# Найти ответ нам поможет пример. Объединим ratings_dates с movies по ключевому столбцу movieId, 
# но с параметром how='outer' (full outer) и выведем размер таблицы, а также её «хвост»:

merged2 = ratings_dates.merge(
    movies,
    on='movieId',
    how='outer'
)
print('Число строк в таблице merged2: ', merged2.shape[0])
display(merged2.tail())

Число строк в таблице merged2:  100854

,userId,movieId,rating,date,title,genres
100849,184.0,193581,4.0,2018-09-16 14:44:42,Black Butler: Book of the Atlantic (2017),Action|Animation|Comedy|Fantasy
100850,184.0,193583,3.5,2018-09-16 14:52:25,No Game No Life: Zero (2017),Animation|Comedy|Fantasy
100851,184.0,193585,3.5,2018-09-16 14:56:45,Flint (2017),Drama
100852,184.0,193587,3.5,2018-09-16 15:00:21,Bungo Stray Dogs: Dead Apple (2018),Action|Animation
100853,331.0,193609,4.0,2018-09-17 04:13:26,Andrew Dice Clay: Dice Rules (1991),Comedy

In [ ]:
# Метод merge() с внешним (outer) типом объединения может использоваться как аналог метода concat() при объединении таблиц 
# с одинаковой структурой (одинаковые количество и названия столбцов) по строкам. В таком случае все одноимённые столбцы таблиц будут считаться ключевыми.
# Рассмотрим пример: объединим таблицы ratings1 и ratings2, как мы уже делали раньше, но теперь используем метод merge():

merge_ratings = ratings1.merge(ratings2, how='outer')
print('Число строк в таблице merge_ratings: ', merge_ratings.shape[0])
display(merge_ratings)

# Обратите внимание, что при использовании метода merge() для склейки двух таблиц у нас автоматически пропали дубликаты, 
# которые мы видели при использовании метода concat(). Это особенность метода merge() — автоматическое удаление дублей.

Число строк в таблице merge_ratings:  100836

        userId  movieId  rating
0            1        1     4.0
1            1        3     4.0
2            1        6     4.0
3            1       47     5.0
4            1       50     5.0
...        ...      ...     ...
100831     610   166534     4.0
100832     610   168248     5.0
100833     610   168250     5.0
100834     610   168252     5.0
100835     610   170875     3.0

[100836 rows x 3 columns]

In [40]:
# Даны две таблицы: items_df, в которой содержится информация о наличии товаров на складе, и purchase_df с данными о покупках товаров.
# Информация в таблицах представлена в виде следующих столбцов:
# item_id — идентификатор модели;
# vendor — производитель модели;
# stock_count — имеющееся на складе количество данных моделей (в штуках);
# purchase_id — идентификатор покупки;
# price — стоимость модели в покупке.
# Вам необходимо сделать следующее:

# Сформируйте DataFrame merged, так чтобы после объединения purchase_df и items_df остались модели, которые учтены на складе и имели продажи.
# На основе таблицы merged найдите суммарную выручку, которую можно было бы получить от продажи всех товаров, имеющихся на складе. Результат занесите в переменную income.

import pandas as pd

items_df = pd.DataFrame({
            'item_id': [417283, 849734, 132223, 573943, 19475, 3294095, 382043, 302948, 100132, 312394],
            'vendor': ['Samsung', 'LG', 'Apple', 'Apple', 'LG', 'Apple', 'Samsung', 'Samsung', 'LG', 'ZTE'],
            'stock_count': [54, 33, 122, 18, 102, 43, 77, 143, 60, 19]
        })

purchase_df = pd.DataFrame({
            'purchase_id': [101, 101, 101, 112, 121, 145, 145, 145, 145, 221],
            'item_id': [417283, 849734, 132223, 573943, 19475, 3294095, 382043, 302948, 103845, 100132],
            'price': [13900, 5330, 38200, 49990, 9890, 33000, 67500, 34500, 89900, 11400]
        })

# Введите свое решение ниже
merged = items_df.merge(purchase_df, how = 'inner')
income = (merged['stock_count']*merged['price']).sum()

print(merged)
print(income)

   item_id   vendor  stock_count  purchase_id  price
0   417283  Samsung           54          101  13900
1   849734       LG           33          101   5330
2   132223    Apple          122          101  38200
3   573943    Apple           18          112  49990
4    19475       LG          102          121   9890
5  3294095    Apple           43          145  33000
6   382043  Samsung           77          145  67500
7   302948  Samsung          143          145  34500
8   100132       LG           60          221  11400
19729490

In [41]:
ratings_movies_orig = pd.read_csv('data/ratings_movies.csv')
ratings_movies = ratings_movies_orig.copy()

display(ratings_movies)

,Unnamed: 0,userId,movieId,rating,date,title,genres
0,0,1,1,4.0,2000-07-30 18:45:03,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy
1,1,1,3,4.0,2000-07-30 18:20:47,Grumpier Old Men (1995),Comedy|Romance
2,2,1,6,4.0,2000-07-30 18:37:04,Heat (1995),Action|Crime|Thriller
3,3,1,47,5.0,2000-07-30 19:03:35,Seven (a.k.a. Se7en) (1995),Mystery|Thriller
4,4,1,50,5.0,2000-07-30 18:48:51,"Usual Suspects, The (1995)",Crime|Mystery|Thriller
...,...,...,...,...,...,...,...
100831,100831,610,166534,4.0,2017-05-03 21:53:22,Split (2017),Drama|Horror|Thriller
100832,100832,610,168248,5.0,2017-05-03 22:21:31,John Wick: Chapter Two (2017),Action|Crime|Thriller
100833,100833,610,168250,5.0,2017-05-08 19:50:47,Get Out (2017),Horror
100834,100834,610,168252,5.0,2017-05-03 21:19:12,Logan (2017),Action|Sci-Fi
100835,100835,610,170875,3.0,2017-05-03 21:20:15,The Fate of the Furious (2017),Action|Crime|Drama|Thriller

In [42]:
#библиотека для регулярных выражений
import re 
def get_year_release(arg):
    #находим все слова по шаблону "(DDDD)"
    candidates = re.findall(r'\(\d{4}\)', arg) 
    # проверяем число вхождений
    if len(candidates) > 0:
        #если число вхождений больше 0,
	#очищаем строку от знаков "(" и ")"
        year = candidates[0].replace('(', '')
        year = year.replace(')', '')
        return int(year)
    else:
        #если год не указан, возвращаем None
        return None

In [58]:
# Создайте в таблице новый признак year_release, который соответствует году выпуска фильма.
# У скольких фильмов не указан год их выпуска?
ratings_movies['year_release'] = ratings_movies['title'].apply(get_year_release)
ratings_movies.head()
ratings_movies['year_release'].info()
display(ratings_movies['year_release'].isna().sum())

<class 'pandas.core.series.Series'>
RangeIndex: 100836 entries, 0 to 100835
Series name: year_release
Non-Null Count   Dtype
--------------   -----
100818 non-null  float64
dtypes: float64(1)
memory usage: 787.9 KB

np.int64(18)

In [79]:
# Какой фильм, выпущенный в 1999 году, получил наименьшую среднюю оценку зрителей?
# В качестве ответа запишите название этого фильма без указания года его выпуска.

ratings_movies[ratings_movies['year_release'] == 1999].groupby('title')['rating'].mean().sort_values()

title
Bloodsport: The Dark Kumite (1999)                  0.5
Trippin' (1999)                                     1.0
Chill Factor (1999)                                 1.0
From Dusk Till Dawn 2: Texas Blood Money (1999)     1.0
Simon Sez (1999)                                    1.0
                                                   ...
Mickey's Once Upon a Christmas (1999)               5.0
On the Ropes (1999)                                 5.0
Trailer Park Boys (1999)                            5.0
Five Senses, The (1999)                             5.0
George Carlin: You Are All Diseased (1999)          5.0
Name: rating, Length: 261, dtype: float64

In [80]:
# Какое сочетание жанров фильмов (genres), выпущенных в 2010 году, получило наименьшую среднюю оценку (rating)?
# Запишите сочетание так же, как оно указано в таблице (через разделитель |, без пробелов).
ratings_movies[ratings_movies['year_release'] == 2010].groupby('genres')['rating'].mean().sort_values()

genres
Action|Sci-Fi                        1.000000
Action|Adventure|Horror              1.500000
Action|Drama|Fantasy                 1.500000
Crime|Romance                        1.500000
Adventure|Comedy|Fantasy             1.833333
                                       ...
Crime                                4.750000
Adventure|Children|Comedy|Mystery    5.000000
Animation|Children|Mystery           5.000000
Animation|Drama|Fantasy|Mystery      5.000000
Comedy|Musical                       5.000000
Name: rating, Length: 119, dtype: float64

In [84]:
# Какой пользователь (userId) посмотрел наибольшее количество различных (уникальных) комбинаций жанров (genres) фильмов? 
# В качестве ответа запишите идентификатор этого пользователя.
ratings_movies.groupby('userId')['genres'].nunique().sort_values()

userId
245     13
85      13
214     13
494     15
578     15
      ...
474    395
380    399
448    403
414    482
599    524
Name: genres, Length: 610, dtype: int64

In [88]:
# Найдите пользователя, который выставил наименьшее количество оценок, но его средняя оценка фильмам наибольшая.
# В качестве ответа укажите идентификатор этого пользователя.
# Чтобы рассчитать несколько параметров для каждого пользователя (количество оценок и среднюю оценку), можно воспользоваться методом agg() на сгруппированных данных.

# DataFrame.groupby(by=None, axis=<no_default>, level=None, as_index=True, sort=True, group_keys=True, observed=<no_default>, dropna=True)[source]

user_stats = ratings_movies.groupby('userId').agg(
    mean_rating=('rating', 'mean'),
    rating_count=('rating', 'count')
)
print(user_stats)

# Находим минимальное количество оценок
min_count = user_stats['rating_count'].min()
print(min_count)


# Отбираем пользователей с этим минимальным количеством
few_users = user_stats[user_stats['rating_count'] == min_count]
print(few_users)

# Среди них ищем пользователя с наибольшей средней оценкой
best_user = few_users['mean_rating'].idxmax()

print(best_user)

        mean_rating  rating_count
userId
1          4.366379           232
2          3.948276            29
3          2.435897            39
4          3.555556           216
5          3.636364            44
...             ...           ...
606        3.657399          1115
607        3.786096           187
608        3.134176           831
609        3.270270            37
610        3.688556          1302

[610 rows x 2 columns]
20
        mean_rating  rating_count
userId
53            5.000            20
147           3.375            20
189           4.100            20
194           3.475            20
207           2.875            20
257           3.200            20
278           3.875            20
320           3.525            20
406           3.250            20
431           2.725            20
442           1.275            20
569           4.000            20
576           3.100            20
595           4.200            20
53

In [97]:
# Найдите сочетание жанров (genres) за 2018 год, которое имеет наибольший средний рейтинг (среднее по столбцу rating), 
# и при этом число выставленных ему оценок (количество значений в столбце rating) больше 10.
# Запишите сочетание так же, как оно указано в таблице (через разделитель |, без пробелов).

genres_stats = ratings_movies[ratings_movies['year_release'] == 2018].groupby('genres').agg(
    mean_rating=('rating', 'mean'),
    rating_count=('rating', 'count')
)
print(genres_stats)

genres_rated_more_ten = genres_stats[genres_stats['rating_count']>10]
print(genres_rated_more_ten)

genres_mean_max = genres_rated_more_ten['mean_rating'].max()
print(genres_mean_max)

few_genres = genres_rated_more_ten[genres_rated_more_ten['mean_rating'] == genres_mean_max]
print(few_genres)

                                        mean_rating  rating_count
genres
Action|Adventure|Animation|Children        3.000000             4
Action|Adventure|Children|Sci-Fi           3.900000             5
Action|Adventure|Comedy|Fantasy|Sci-Fi     3.666667             3
Action|Adventure|Drama|Sci-Fi|Thriller     3.250000             2
Action|Adventure|Fantasy                   2.500000             4
Action|Adventure|Sci-Fi                    3.928571            14
Action|Adventure|Thriller                  3.750000             2
Action|Animation                           3.500000             1
Action|Comedy                              3.000000             1
Action|Comedy|Crime|Horror                 4.000000             1
Action|Comedy|Sci-Fi                       3.875000            12
Action|Crime|Drama|Thriller                4.000000             1
Action|Crime|Thriller                      2.500000             1
Action|Fantasy|Sci-Fi                      2.750000             2
Action|Mystery|Sci-Fi|Thriller             3.500000             1
Adventure|Children|Fantasy|Sci-Fi          3.000000             1
Adventure|Comedy|Fantasy                   4.500000             1
Adventure|Mystery|Sci-Fi|Thriller          3.833333             3
Adventure|Thriller                         4.500000             1
Animation|Comedy                           3.500000             5
Comedy                                     3.312500             8
Comedy|Crime|Drama                         2.500000             1
Comedy|Drama                               3.250000             2
Comedy|Fantasy|Sci-Fi                      4.500000             1
Comedy|Romance                             4.500000             1
Crime|Drama                                3.500000             1
Crime|Drama|Mystery|Thriller               1.500000             1
Documentary                                4.000000             2
Drama|Fantasy|Thriller                     2.000000             1
Drama|Horror|Thriller                      2.750000             4
Horror|Mystery|Sci-Fi|Thriller             2.250000             2
Horror|Mystery|Thriller                    3.500000             1
Sci-Fi|Thriller                            3.500000             1
                         mean_rating  rating_count
genres
Action|Adventure|Sci-Fi     3.928571            14
Action|Comedy|Sci-Fi        3.875000            12
3.9285714285714284
                         mean_rating  rating_count
genres
Action|Adventure|Sci-Fi     3.928571            14

In [109]:
# Добавьте в таблицу новый признак year_rating — год выставления оценки. Создайте сводную таблицу, 
# которая иллюстрирует зависимость среднего рейтинга фильма от года выставления оценки и жанра. 
# Выберите верные варианты ответа, исходя из построенной таблицы:

ratings_movies['year_rating'] = pd.to_datetime(ratings_movies['date']).dt.year
ratings_movies.head()

pivot = ratings_movies.pivot_table(
    values='rating',
    index='year_rating',
    columns='genres',
    aggfunc=['mean'],
    fill_value=0
)

pivot

                          mean                             \
genres      (no genres listed)    Action Action|Adventure
year_rating
1996                  0.000000  2.730769         3.454545
1997                  0.000000  3.538462         4.150000
1998                  0.000000  0.000000         4.200000
1999                  0.000000  0.000000         4.000000
2000                  0.000000  2.588235         3.738462
2001                  0.000000  3.000000         3.500000
2002                  0.000000  2.750000         4.304348
2003                  0.000000  3.833333         3.277778
2004                  0.000000  2.700000         4.136364
2005                  0.000000  3.357143         3.413043
2006                  0.000000  2.166667         4.090909
2007                  0.000000  2.583333         3.666667
2008                  0.000000  3.000000         3.656250
2009                  0.000000  0.000000         3.714286
2010                  0.000000  3.500000         3.437500
2011                  0.000000  4.500000         3.888889
2012                  0.000000  2.625000         3.900000
2013                  0.000000  2.500000         3.833333
2014                  0.000000  0.000000         3.875000
2015                  0.500000  3.100000         3.560976
2016                  3.500000  3.545455         3.722222
2017                  3.000000  2.637931         3.527778
2018                  3.676471  2.588235         3.397436

                                                                            \
genres      Action|Adventure|Animation Action|Adventure|Animation|Children
year_rating
1996                             0.000                            0.000000
1997                             0.000                            0.000000
1998                             0.000                            0.000000
1999                             0.000                            0.000000
2000                             0.000                            0.000000
2001                             0.000                            0.000000
2002                             0.000                            0.000000
2003                             0.000                            0.000000
2004                             0.000                            0.000000
2005                             0.000                            0.000000
2006                             0.000                            0.000000
2007                             0.000                            0.000000
2008                             0.000                            0.000000
2009                             0.000                            0.000000
2010                             0.000                            0.000000
2011                             0.000                            0.000000
2012                             0.000                            4.000000
2013                             0.000                            3.000000
2014                             3.000                            3.500000
2015                             3.800                            3.666667
2016                             3.750                            3.833333
2017                             3.375                            3.500000
2018                             3.650                            3.166667

                                                        \
genres      Action|Adventure|Animation|Children|Comedy
year_rating
1996                                          0.000000
1997                                          0.000000
1998                                          0.000000
1999                                          0.000000
2000                                          0.000000
2001                                          0.000000
2002                                          0.000000
2003                                          0.000000
2004                                          4.000000
2005                                          4.107143
2006                                          3.833333
2007                                          3.846154
2008                                          4.125000
2009                                          3.900000
2010                                          4.333333
2011                                          3.500000
2012                                          3.785714
2013                                          4.333333
2014                                          3.250000
2015                                          3.565217
2016                                          3.925000
2017                                          3.676471
2018                                          3.741935

                                                                \
genres      Action|Adventure|Animation|Children|Comedy|Fantasy
year_rating
1996                                                  0.000000
1997                                                  0.000000
1998                                                  0.000000
1999                                                  0.000000
2000                                                  0.000000
2001                                                  0.000000
2002                                                  0.000000
2003                                                  0.000000
2004                                                  0.000000
2005                                                  0.000000
2006                                                  0.000000
2007                                                  3.000000
2008                                                  4.000000
2009                                                  0.000000
2010                                                  0.000000
2011                                                  0.000000
2012                                                  0.000000
2013                                                  0.000000
2014                                                  3.833333
2015                                                  3.833333
2016                                                  3.388889
2017                                                  3.700000
2018                                                  4.142857

                                                             \
genres      Action|Adventure|Animation|Children|Comedy|IMAX
year_rating
1996                                               0.000000
1997                                               0.000000
1998                                               0.000000
1999                                               0.000000
2000                                               0.000000
2001                                               0.000000
2002                                               0.000000
2003                                               0.000000
2004                                               0.000000
2005                                               0.000000
2006                                               0.000000
2007                                               0.000000
2008                                               0.000000
2009                                               3.250000
2010                                               3.500000
2011                                               0.000000
2012                                               3.550000
2013                                               5.000000
2014                                               3.500000
2015                                               3.375000
2016                                               3.666667
2017                                               1.000000
2018                                               3.700000

                                                                \
genres      Action|Adventure|Animation|Children|Comedy|Romance
year_rating
1996                                                  0.000000
1997                                                  0.000000
1998                                                  0.000000
1999                                                  0.000000
2000                                                  0.000000
2001                                                  0.000000
2002                                                  0.000000
2003                                                  0.000000
2004                                                  0.000000
2005                                                  0.000000
2006                                                  0.000000
2007                                                  0.000000
2008                                                  0.000000
2009                                                  0.000000
2010                                                  3.000000
2011                                                  0.000000
2012                                                  4.000000
2013                                                  0.000000
2014                                                  4.000000
2015                                                  2.333333
2016                                                  1.000000
2017                                                  1.000000
2018                                                  2.500000

                                                               ...  \
genres      Action|Adventure|Animation|Children|Comedy|Sci-Fi  ...
year_rating                                                    ...
1996                                                      0.0  ...
1997                                                      0.0  ...
1998                                                      0.0  ...
1999                                                      0.0  ...
2000                                                      0.0  ...
2001                                                      0.0  ...
2002                                                      0.0  ...
2003                                                      0.0  ...
2004                                                      0.0  ...
2005                                                      0.0  ...
2006                                                      3.0  ...
2007                                                      2.8  ...
2008                                                      3.5  ...
2009                                                      2.5  ...
2010                                                      0.0  ...
2011                                                      4.0  ...
2012                                                      0.0  ...
2013                                                      0.0  ...
2014                                                      0.0  ...
2015                                                      2.5  ...
2016                                                      4.0  ...
2017                                                      2.0  ...
2018                                                      4.0  ...

                                                                    \
genres      Romance|Thriller Romance|War Romance|Western    Sci-Fi
year_rating
1996                   0.000         0.0             0.0  0.000000
1997                   0.000         0.0             0.0  0.000000
1998                   0.000         0.0             0.0  0.000000
1999                   2.000         0.0             0.0  0.000000
2000                   4.000         0.0             3.0  3.416667
2001                   0.000         0.0             3.0  2.500000
2002                   3.000         0.0             0.0  3.750000
2003                   3.375         2.5             0.0  2.333333
2004                   3.000         3.0             3.5  2.125000
2005                   2.000         0.0             0.0  3.000000
2006                   0.000         0.0             0.0  0.500000
2007                   1.500         0.0             2.5  3.375000
2008                   0.000         0.0             0.0  3.125000
2009                   0.000         0.0             0.0  2.000000
2010                   0.000         0.0             0.0  4.000000
2011                   0.000         0.0             0.0  3.500000
2012                   2.500         0.0             0.0  4.166667
2013                   0.000         0.0             0.0  1.500000
2014                   0.000         0.0             0.0  2.500000
2015                   0.000         0.0             0.0  2.900000
2016                   2.500         0.0             0.0  3.555556
2017                   3.000         0.0             0.0  3.864865
2018                   0.000         0.0             0.0  3.128571

                                                                             \
genres      Sci-Fi|IMAX Sci-Fi|Thriller Sci-Fi|Thriller|IMAX  Thriller  War
year_rating
1996           0.000000        2.666667             0.000000  3.838095  0.0
1997           0.000000        3.400000             0.000000  3.923077  0.0
1998           0.000000        0.000000             0.000000  3.800000  0.0
1999           0.000000        4.000000             0.000000  3.700000  4.5
2000           0.000000        2.142857             0.000000  3.087912  3.0
2001           0.000000        2.500000             0.000000  3.477273  3.0
2002           0.000000        3.600000             0.000000  3.583333  3.5
2003           0.000000        3.142857             0.000000  3.250000  3.0
2004           0.000000        0.000000             0.000000  3.464286  3.0
2005           0.000000        2.750000             0.000000  3.411765  0.0
2006           0.000000        4.500000             0.000000  3.735294  0.0
2007           0.000000        2.833333             0.000000  3.421875  0.0
2008           0.000000        3.000000             0.000000  3.333333  0.0
2009           0.000000        4.000000             0.000000  2.964286  4.0
2010           0.000000        2.500000             0.000000  2.833333  0.0
2011           0.000000        1.833333             4.000000  3.625000  0.0
2012           0.000000        3.500000             3.666667  3.083333  0.0
2013           0.000000        3.833333             4.000000  3.666667  0.0
2014           5.000000        0.000000             4.000000  4.000000  0.0
2015           4.071429        3.764706             4.000000  2.911765  0.0
2016           3.807692        3.916667             3.666667  3.432432  0.0
2017           4.264706        3.750000             2.500000  3.152174  0.0
2018           3.500000        3.562500             0.000000  3.296296  0.0


genres        Western
year_rating
1996         3.117647
1997         3.000000
1998         0.000000
1999         4.000000
2000         4.058824
2001         3.111111
2002         3.000000
2003         4.000000
2004         3.800000
2005         4.500000
2006         3.625000
2007         3.000000
2008         4.000000
2009         3.375000
2010         3.666667
2011         4.000000
2012         4.100000
2013         4.000000
2014         4.000000
2015         3.900000
2016         3.958333
2017         2.933333
2018         3.611111

[23 rows x 951 columns]

In [110]:
# За весь период (с 1996 по 2018 год) сочетание жанров Action|Adventure ни разу не получало среднюю оценку ниже 3.
print(pivot[('mean', 'Action|Adventure')])

year_rating
1996    3.454545
1997    4.150000
1998    4.200000
1999    4.000000
2000    3.738462
2001    3.500000
2002    4.304348
2003    3.277778
2004    4.136364
2005    3.413043
2006    4.090909
2007    3.666667
2008    3.656250
2009    3.714286
2010    3.437500
2011    3.888889
2012    3.900000
2013    3.833333
2014    3.875000
2015    3.560976
2016    3.722222
2017    3.527778
2018    3.397436
Name: (mean, Action|Adventure), dtype: float64

In [111]:
# Наилучшую оценку жанр Action|Adventure|Animation|Children|Comedy|IMAX получил в 2010 году.
print(pivot[('mean', 'Action|Adventure|Animation|Children|Comedy|IMAX')])

year_rating
1996    0.000000
1997    0.000000
1998    0.000000
1999    0.000000
2000    0.000000
2001    0.000000
2002    0.000000
2003    0.000000
2004    0.000000
2005    0.000000
2006    0.000000
2007    0.000000
2008    0.000000
2009    3.250000
2010    3.500000
2011    0.000000
2012    3.550000
2013    5.000000
2014    3.500000
2015    3.375000
2016    3.666667
2017    1.000000
2018    3.700000
Name: (mean, Action|Adventure|Animation|Children|Comedy|IMAX), dtype: float64

In [115]:
# Среди сочетаний жанров, получивших наивысшую среднюю оценку в 2018 году, есть сочетание Animation|Children|Mystery.
year_2018 = pivot.loc[2018].sort_values()
print(year_2018.tail(15))

      genres
mean  Drama|Romance|War                            5.0
      Mystery|Romance|Sci-Fi|Thriller              5.0
      Action|Comedy|Documentary                    5.0
      Romance|Sci-Fi                               5.0
      Animation|Comedy|Fantasy|Musical             5.0
      Animation|Comedy|Drama|Fantasy|Sci-Fi        5.0
      Animation|Comedy|Drama                       5.0
      Comedy|Fantasy|Horror|Musical|Thriller       5.0
      Animation|Children|Mystery                   5.0
      Comedy|Horror|Mystery                        5.0
      Adventure|Children|Comedy|Fantasy|Mystery    5.0
      Animation|Crime|Drama                        5.0
      Comedy|Drama|Fantasy|Mystery|Romance         5.0
      Comedy|Crime|Fantasy                         5.0
      Comedy|Crime|Horror|Thriller                 5.0
Name: 2018, dtype: float64

In [116]:
# Для жанра Comedy прослеживается тенденция падения рейтинга с каждым годом (с 1996 по 2018).
print(pivot[('mean', 'Comedy')])

year_rating
1996    3.228571
1997    3.409091
1998    3.000000
1999    3.606061
2000    3.141291
2001    3.318408
2002    3.198556
2003    3.120066
2004    3.356877
2005    2.963325
2006    3.347534
2007    2.928187
2008    3.426667
2009    3.273292
2010    3.179825
2011    3.232877
2012    3.478477
2013    3.489474
2014    3.271429
2015    3.106183
2016    3.373431
2017    2.852668
2018    3.121296
Name: (mean, Comedy), dtype: float64

In [130]:
# Дано два файла:
# orders.csv, содержащий данные о заказах;
# products.csv, содержащий данные о товарах.

orders_orig = pd.read_csv('data/orders.csv', sep=';') #, encoding='utf-8')
orders = orders_orig.copy()

display(orders)

,Дата создания,Order ID,ID Покупателя,Статус,Оплачен,Отменен,Отгружен,ID товара,Количество
0,09.11.2019 21:55:51,9,10,"Принят, ожидается оплата",Нет,Нет,Нет,103,5
1,09.11.2019 15:05:57,8,9,"Принят, ожидается оплата",Нет,Нет,Нет,86,100
2,09.11.2019 15:05:57,8,9,"Принят, ожидается оплата",Нет,Нет,Нет,104,10
3,09.11.2019 12:50:07,7,8,"Принят, ожидается оплата",Нет,Нет,Нет,104,7
4,09.11.2019 12:00:00,6,1,"Принят, ожидается оплата",Нет,Нет,Нет,104,5
5,09.11.2019 12:00:00,6,1,"Принят, ожидается оплата",Нет,Нет,Нет,103,5
6,08.11.2019 08:36:22,5,5,Отменён,Нет,Да,Нет,124,1
7,08.11.2019 08:36:22,4,9,"Принят, ожидается оплата",Нет,Нет,Да,91,1
8,08.11.2019 08:36:22,3,8,"Оплачен, формируется к отправке",Да,Нет,Нет,103,3
9,08.11.2019 08:36:22,3,8,"Оплачен, формируется к отправке",Да,Нет,Нет,104,3
10,08.11.2019 08:36:21,2,7,Выполнен,Да,Нет,Да,74,1
11,08.11.2019 08:36:21,2,7,Выполнен,Да,Нет,Да,53,1
12,08.11.2019 08:36:21,2,7,Выполнен,Да,Нет,Да,137,1
13,08.11.2019 08:36:21,2,7,Выполнен,Да,Нет,Да,47,1
14,08.11.2019 08:36:20,1,5,"Оплачен, формируется к отправке",Да,Нет,Нет,71,1
15,08.11.2019 08:36:20,1,5,"Оплачен, формируется к отправке",Да,Нет,Нет,86,1
16,08.11.2019 08:36:20,1,5,"Оплачен, формируется к отправке",Да,Нет,Нет,51,1
17,01.01.2001 00:00:00,0,1,"Оплачен, формируется к отправке",Да,Нет,Нет,666,1

In [129]:
products_orig = pd.read_csv('data/products.csv', sep=';') #, encoding='utf-8')
products = products_orig.copy()

display(products)

    Product_ID                                   Name  Price CURRENCY
0           47                   Шатны Полосатый рейс   2999      RUR
1           51               Платье Аленький цветочек   4999      RUR
2           53                 Штаны Цветочная Поляна   4999      RUR
3           71                    Платье Ночная Жизнь   7999      RUR
4           74               Платье Ночная Жизнь XXXL   8999      RUR
5           86                     Носки Простые, муж     45      RUR
6           91                     Носки Честные, муж     50      RUR
7          103                  Носки Подарочные, муж    199      RUR
8          104                  Носки Подарочные, жен    249      RUR
9          124                   Носки беговые Camino    999      RUR
10         137              Гольфы детские Снегурочка     99      RUR
11         138               Гольфы детские Питер Пен     99      RUR
12         139                       Сумка для носков    500      RUR
13         140  Товар, которому не придумано название      1      RUR

In [131]:
# Объедините заданные таблицы в таблицу orders_products, чтобы в результирующей таблице оказалась информация обо всех заказах, 
# но не оказалось информации о продуктах, на которых заказов ещё не поступало. 

orders_products = orders.join(
    products.set_index('Product_ID'), # правая
    on='ID товара', # левая
    how='left'
)

orders_products

,Дата создания,Order ID,ID Покупателя,Статус,Оплачен,Отменен,Отгружен,ID товара,Количество,Name,Price,CURRENCY
0,09.11.2019 21:55:51,9,10,"Принят, ожидается оплата",Нет,Нет,Нет,103,5,"Носки Подарочные, муж",199.0,RUR
1,09.11.2019 15:05:57,8,9,"Принят, ожидается оплата",Нет,Нет,Нет,86,100,"Носки Простые, муж",45.0,RUR
2,09.11.2019 15:05:57,8,9,"Принят, ожидается оплата",Нет,Нет,Нет,104,10,"Носки Подарочные, жен",249.0,RUR
3,09.11.2019 12:50:07,7,8,"Принят, ожидается оплата",Нет,Нет,Нет,104,7,"Носки Подарочные, жен",249.0,RUR
4,09.11.2019 12:00:00,6,1,"Принят, ожидается оплата",Нет,Нет,Нет,104,5,"Носки Подарочные, жен",249.0,RUR
5,09.11.2019 12:00:00,6,1,"Принят, ожидается оплата",Нет,Нет,Нет,103,5,"Носки Подарочные, муж",199.0,RUR
6,08.11.2019 08:36:22,5,5,Отменён,Нет,Да,Нет,124,1,Носки беговые Camino,999.0,RUR
7,08.11.2019 08:36:22,4,9,"Принят, ожидается оплата",Нет,Нет,Да,91,1,"Носки Честные, муж",50.0,RUR
8,08.11.2019 08:36:22,3,8,"Оплачен, формируется к отправке",Да,Нет,Нет,103,3,"Носки Подарочные, муж",199.0,RUR
9,08.11.2019 08:36:22,3,8,"Оплачен, формируется к отправке",Да,Нет,Нет,104,3,"Носки Подарочные, жен",249.0,RUR
10,08.11.2019 08:36:21,2,7,Выполнен,Да,Нет,Да,74,1,Платье Ночная Жизнь XXXL,8999.0,RUR
11,08.11.2019 08:36:21,2,7,Выполнен,Да,Нет,Да,53,1,Штаны Цветочная Поляна,4999.0,RUR
12,08.11.2019 08:36:21,2,7,Выполнен,Да,Нет,Да,137,1,Гольфы детские Снегурочка,99.0,RUR
13,08.11.2019 08:36:21,2,7,Выполнен,Да,Нет,Да,47,1,Шатны Полосатый рейс,2999.0,RUR
14,08.11.2019 08:36:20,1,5,"Оплачен, формируется к отправке",Да,Нет,Нет,71,1,Платье Ночная Жизнь,7999.0,RUR
15,08.11.2019 08:36:20,1,5,"Оплачен, формируется к отправке",Да,Нет,Нет,86,1,"Носки Простые, муж",45.0,RUR
16,08.11.2019 08:36:20,1,5,"Оплачен, формируется к отправке",Да,Нет,Нет,51,1,Платье Аленький цветочек,4999.0,RUR
17,01.01.2001 00:00:00,0,1,"Оплачен, формируется к отправке",Да,Нет,Нет,666,1,NaN,NaN,NaN

In [142]:
# Какой покупатель принёс наибольшую суммарную прибыль интернет-магазину за указанный период?
# В ответ запишите идентификатор этого покупателя (ID Покупателя).
# Прибыль состоит только из оплаченных заказов и рассчитывается как количество купленного товара, умноженное на его цену.

print(orders_products[orders_products['Оплачен']=='Да']['Количество']*orders_products[orders_products['Оплачен']=='Да']['Price'])

8      597.0
9      747.0
10    8999.0
11    4999.0
12      99.0
13    2999.0
14    7999.0
15      45.0
16    4999.0
17       NaN
dtype: float64

In [ ]:
# 1. Введение
# Задание 1.1

melb_df['Date'] = pd.to_datetime(melb_df['Date'])
quarters = melb_df['Date'].dt.quarter
print(quarters.value_counts().iloc[1])
# Задание 1.2

cols_to_exclude = ['Date', 'Rooms', 'Bedroom', 'Bathroom', 'Car'] 
max_unique_count = 150 
for col in melb_df.columns: 
    if melb_df[col].nunique() < max_unique_count and col not in cols_to_exclude: 
        melb_df[col] = melb_df[col].astype('category')
display(melb_df.info())
# 2. Сортировка данных в DataFrame
# Задание 2.2

int(melb_df.sort_values(
    by='AreaRatio', 
    ignore_index=True,
    ascending=False
).loc[1558, 'BuildingArea'])
# Задание 2.3

mask1 = melb_df['Type'] == 'townhouse'
mask2 = melb_df['Rooms'] > 2
int(melb_df[mask1&mask2].sort_values(
    by=['Rooms', 'MeanRoomsSquare'],
    ascending=[True, False],
    ignore_index=True
).loc[18, 'Price'])
# 3. Группировка данных в DataFrame
# Задание 3.1

melb_df.groupby('Rooms')['Price'].mean().sort_values(ascending=False)
# Задание 3.2

melb_df.groupby('Regionname')['Lattitude'].std().sort_values()
# Задание 3.3

date1 = pd.to_datetime('2017-05-01')
date2 = pd.to_datetime('2017-09-01')
mask = (date1 <= melb_df['Date']) & (melb_df['Date']<= date2)
melb_df[mask].groupby('SellerG')['Price'].sum().sort_values(ascending=True)
# 4. Сводные таблицы
# Задание 4.2

pivot = melb_df.pivot_table(
    values='BuildingArea',
    index='Type',
    columns='Rooms',
    aggfunc='median',
    fill_value=0
)
display(pivot)
# Задание 4.3

pivot = melb_df.pivot_table(
    values='Price',
    index='SellerG',
    columns='Type',
    aggfunc='median',
)
max_unit_price = pivot['unit'].max()
print(pivot[pivot['unit'] == max_unit_price].index[0])
# 6. Объединение DataFrame: concat
# Задание 6.3

def concat_users_files(path):
    data = pd.DataFrame()
    file_names = os.listdir(path)
    file_names.sort()
    for file in file_names:
        tmp_data = pd.read_csv(path + '/' + file)
        data = pd.concat([data, tmp_data], axis=0, ignore_index=True)
    data = data.drop_duplicates()
    return data
# 7. Объединение DataFrame: join, merge
# Задание 7.5

merged = items_df.merge(purchase_df, how='inner', on='item_id')
income = (merged['price'] * merged['stock_count']).sum()